.github/.ARCHIVARIUS_URL

Created .ARCHIVARIUS_URL

---

.github/workflows/bundle.yml
applications/GPIO/pokemon/manifest.yml

Fixed branch name for workflows

---

documentation/Contributing.md
documentation/Manifest.md
tools/bundle.py

Updated general requirements

---

applications/Tools/vb_migrate/manifest.yml

- This app is designed to make transferring your characters from VB Lab and VBC Lab more convenient.
- **Includes stripped down nfc library for using `nfc_worker`.** This will be updated to use system NFC libraries if and when emulation is included into the API.
- Vital Bracelet device (Vital Bracelet Digimon, Vital Bracelet Characters, Vital Hero, Vital Bracelet BE)
- Vital Bracelet Arena app (note: included instructions refer to VB Lab, which has been discontinued, but a similar workflow can be used on VB Arena; second half of instructions for VB Arena still apply)

Add VB Lab Migration Assistant

---

applications/Tools/air_mouse/manifest.yml

- Flipper Air Mouse
- Needs custom hardware module (all necessary sources for the hardware are provided).

Add FlippAirMouse manifest

---

applications/NFC/mifare_nested/manifest.yml

- Flipper Nested is an application for Mifare Classic nested attacks on Flipper Zero
- Mifare Classic tags

Add Flipper Nested

---

applications/GPIO/esp32_wifi_marauder/manifest.yml

- Application for interfacing with a connected ESP32 chip running Marauder firmware
- Connected ESP32 chip running Marauder firmware

ESP32 WiFi Marauder v0.4.0

---

.github/workflows/build.yml

Additional filtering on build artifacts

---

applications/GPIO/unitemp/manifest.yml

- Unitemp - Universal temperature reader application. Allows for reading temperature, humidity and pressure sensors like a DHT11/22, DS18B20, BMP280, HTU21 and more.
- The application requires external temperature sensors.

Unitemp application

---

applications/GPIO/i2ctools/manifest.yml

A set of i2c tools for Flipper Zero
Any i2c peripherals

Add i2ctools

---

applications/GPIO/lightmeter/manifest.yml

- Lightmeter application based on i2c light sensor. Showing suggested camera settings based on ambient light
- BH1750 sensor

Add lightmeter application

---

applications/USB/bc_scanner/manifest.yml

Emulates a barcode scanner for testing cash registers.  Scanner work at COM-port emulation. 
Characteristics
Speed: 19200 (Bit Rate)
VID: 1155 | PID: 22336
Name: Flipper {Your Flipper name}
Manufacturer Name: Flipper Devices Inc.
SerialNumber=flip_{Your Flipper name}
- None

Add app "bc_scanner"

---

documentation/Manifest.md

Updated categories & docs

---

applications/Media/flizzer_tracker/manifest.yml

Fix crash on new firmware versions
- update flizzer tracker
-

 flizzer tracker: Fix crash on new firmware versions

---

applications/GPIO/air_mouse/manifest.yml

Update air_mouse category

---

applications/GPIO/esp_flasher/manifest.yml

Flashes ESP chips over UART from the flipper.
Requires an ESP chip connected to flipper UART.

Add esp_flasher app

---

applications/NFC/mifare_nested/manifest.yml

Flipper Nested (Update to 1.5.2)

---

applications/GPIO/zeitraffer/README.md
applications/GPIO/zeitraffer/manifest.yml

- Simple timelapse/intervalometer app for Flipper Zero, works via GPIO pins 6 and 7.
- Cable with optocouplers. Assebmly instruction in readme.

add Zeitraffer

---

applications/GPIO/zeitraffer/README.md
applications/GPIO/zeitraffer/manifest.yml

- Simple timelapse/intervalometer app for Flipper Zero, works via GPIO pins 6 and 7.
- Cable with optocouplers. Assebmly instruction in readme.

Theageoflove/zeitraffer 1.1

---

applications/GPIO/lightmeter/manifest.yml

- Lightmeter application based on i2c light sensor. Showing suggested camera settings based on ambient light
- BH1750/MAX44009 sensor

Update lightmeter to 1.1

---

.github/PULL_REQUEST_TEMPLATE.md
documentation/Manifest.md

Updated PR template

---

applications/iButton/fuzzer_ibtn/manifest.yml

- Flipper Zero app for checking ibutton readers
- Version update

iButton Fuzzer v1.1

---

applications/RFID/fuzzer_rfid/manifest.yml

- Flipper Zero app for checking LF RFID readers
- no

RFID Fuzzer v1.1

---

applications/Tools/totp/manifest.yml

Updated [Flipper Authenticator](https://github.com/akopachov/flipper-zero_authenticator) to latest version [v2.3.0](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v2.3.0)
No

Updated Flipper Authenticator to v2.3.0

---

.github/workflows/widget.yml

Fix application name to id

---

.github/workflows/build.yml
tools/requirements.txt

Updated build.yml to match backend 

---

tools/bundle.py

bundler: allowed mobile app screenshots

---

applications/Games/chess/manifest.yml

Updated icon to black on white

---

applications/GPIO/lightmeter/manifest.yml

Lightmeter v1.2

---

applications/Games/color_guess/manifest.yml

- Color Guessing Game using HEX Codes like in HTML
- None

Added Color Guess Game

---

applications/Games/rock_paper_scissors/manifest.yml

- v1.4: Updated Description (contribution from Nikita Kulikov).
Two players (on two Flipper Zeros) play a game of Rock, Paper, Scissors. The user can choose if they want to share contact information (like a YouTube channel) or if they just want to share their Flipper Zero name. Then one player will Host a game. They choose the frequency and the game number. The second person will Join a game (they choose the frequency) and then select one of the game numbers that are being broadcast from a host. Game play - both players press OK at same time, then both players press OK at same time again, then each player chooses UP [Rock], Right [Paper], Down [Scissors]. Rock beats Scissors. Paper beats Rock. Scissors beats Paper. Tie happens if both players pick the same choice. Then you can choose to …

Update description (v1.4)

---

applications/Infrared/xremote/README.md
applications/Infrared/xremote/manifest.yml

- Application that allows to Chain IR Commands and also add pauses inbetween them
- Future version should also include SubGhz commands
- None

Leedave/xremote 0.8

---

.github/workflows/bundle.yml

workflow: bundle: disabled lint checks

---

applications/GPIO/flipperscope/manifest.yml

Simple oscilloscope type application that graphs analogue voltages
and calculate min/max voltages along with the frequency of the signal.
Simply attach a signal generator etc. to pin C0 of the flipper zero

Flipperscope manifest

---

applications/Tools/orgasmotron/README.md
applications/Tools/orgasmotron/manifest.yml

- Allows Flipper Zero to vibrate in different modes
- None

Added orgasmotron app

---

applications/Games/chess/manifest.yml

Chess - update to v1.8 with some bug fixes
N/A

Chess v1.8

---

applications/RFID/key_generator/README.md
applications/RFID/key_generator/manifest.yml

- Added key_generator and removed the one that was automatically generated
- none

Added "EM4100 key generator" app

---

applications/GPIO/esp32_wifi_marauder/manifest.yml

Update wifi marauder app to v0.6.0

Update wifi marauder app

---

applications/Tools/passgen/manifest.yml

Updates include:
- Fixes manifest to indicate FAP (not integrated firmware extension)
- Enable build via `ufbt`
- Removes bias in selected password characters
- More efficient use of furi's TRNG APIs
- Enables CI-based (automated) builds
- N/A
**TWO NOTES:**
1. The second checkbox is for the changes, as this is only an **_update_** to an existing submission.
2. Attempts to validate failed repeatedly with error that appears unrelated to changes:
```ModuleNotFoundError: No module named 'dataclass_wizard'```

Update: passgen app

---

applications/GPIO/camera_suite/README.md
applications/GPIO/camera_suite/manifest.yml

Adds v1.1.0 of the ESP32-CAM software "[ESP32] Camera Suite" (https://github.com/CodyTolene/Flipper-Zero-Camera-Suite). This software has multiple views for settings, guiding the user, and for displaying the camera. The camera has multiple in-use options using various keys on the Flipper Zero, and the camera can be rotated to fit your module placement.
- An ESP32-CAM module is needed. Hardware setup and installation guide [here](https://github.com/CodyTolene/Flipper-Zero-Camera-Suite#hardware-installation).
- Custom firmware is needed on the ESP32-CAM module. See [here](https://github.com/CodyTolene/Flipper-Zero-Camera-Suite#firmware-installation) for more details.

Add '[ESP32] Camera Suite' application.

---

applications/NFC/seader/manifest.yml

- Update of seader to v1.1
- Still requires SAM-UART adapter and HID SAM

Seader 1.1

---

applications/Tools/totp/manifest.yml

- Updated Authenticator to [v3.2.0](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v3.2.0)
- No

Updated Authenticator to v3.2.0

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build.yml
.github/workflows/bundle.yml
documentation/Contributing.md

Updated manifest processing

---

.github/workflows/bundle.yml

Disabled fail-fast for large app batches

---

.github/workflows/bundle.yml
.github/workflows/checklist.yml

Added auto diffs

---

.github/workflows/bundle.yml

Improved diff output logic for forks

---

applications/Infrared/xbox_controller/manifest.yml

Infrared remote control for Xbox One
I'm an author of this Application, and this is original Repo of the project

Change `Xbox Controller` source to the original maintainer repository

---

applications/GPIO/camera_suite/manifest.yml

- Update "[ESP32] Camera Suite" application to [v1.2.0](https://github.com/CodyTolene/Flipper-Zero-Camera-Suite/releases/tag/v1.2.0).
- Includes FAP and ESP32-CAM firmware updates.
- Update Flipper Application Catalog screenshot(s) and doc(s) for "[ESP32] Camera Suite".

Update Camera Suite application to version `1.2.0`

---

applications/Games/dice_app/manifest.yml

- D&D like dice app for Flipper Zero
- App does not require any extra hardware or software

Dice app update to version 1.1

---

applications/Tools/flipbip/manifest.yml

feat: adding ZEC

---

applications/GPIO/air_mouse/manifest.yml

Fixes for firmware 0.88
- Updating existing application
- Nothing changed

Update manifest for air_mouse

---

applications/Tools/totp/manifest.yml

Updated Flipper Authenticator to [v4.0.1](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v4.0.1)
No

Updated Flipper Authenticator to v4.0.1

---

applications/GPIO/ublox/manifest.yml

App to display and log data from u-blox GPS modules over I2C
- u-blox series 8 or 9 GPS with I2C connection, like a [Sparkfun SAM-M8Q module](https://www.sparkfun.com/products/15210)

u-blox GPS app

---

applications/Tools/flipbip/manifest.yml

FlipBIP v1.13

---

applications/Sub-GHz/weather_station/manifest.yml
applications/USB/mass_storage/manifest.yml

- Updated weather_station and mass_storage to 1.1

Updated weather_station and mass_storage to 1.1

---

applications/Bluetooth/hid_ble/README.md
applications/GPIO/avr_isp/README.md
applications/GPIO/dap_link/README.md
applications/GPIO/flipperscope/README.md
applications/GPIO/signal_generator/README.md
applications/GPIO/spi_mem_manager/README.md
applications/GPIO/ublox/README.md
applications/Games/chess/README.md
applications/NFC/mfkey32/README.md
applications/NFC/nfc_magic/README.md
applications/NFC/picopass/README.md
applications/Sub-GHz/weather_station/README.md
applications/Tools/nfc_rfid_detector/README.md
applications/USB/hid_usb/README.md
applications/USB/mass_storage/README.md

Added missing widgets

---

applications/Games/dice_app/manifest.yml

- Fix for roll result randomiser. App version changed to 1.2
- No any extra requires needed

Dice app update to version 1.2

---

applications/GPIO/flipperscope/manifest.yml

Simple oscilloscope type application that graphs analogue voltages
and calculates min/max voltages along with the frequency of the signal.
Now also enables saving waveforms to a file on the SD card.
Simply attach a signal generator etc. to pin C0 of the flipper zero

Bump flipperscope to v0.2

---

applications/Games/racso_ultimate_tic_tac_toe/manifest.yml

- Ultimate Tic-Tac-Toe game for Flipper Zero. Initial release. Can be played by 0, 1 or 2 human players. Has 5 difficulty levels for the AI, with random and Minimax algorithms.
- None.

Ultimate Tic-Tac-Toe 1.0

---

applications/Tools/totp/manifest.yml

- Updated Flipper Authenticator to [v4.0.2](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v4.0.2)
- None

Updated Flipper Authenticator to v4.0.2

---

applications/Games/snake_game/manifest.yml
applications/Media/music_player/manifest.yml
applications/NFC/picopass/manifest.yml
applications/Tools/clock/manifest.yml

- Remaining external apps moved to catalog: Clock, Snake Game, Music player
- Picopass app updates

Clock, snake game, music player from fw repo, picopass updates

---

applications/Games/sudoku/manifest.yml

Classic sudoku game
No extra requirements

Sudoku 1.0

---

applications/GPIO/mh_z19/manifest.yml

It's new application for measuring carbon dioxide (CO2) with mh-z19 sensor and Flipper zero
- Need MH-Z19 sensor
- 5V on GPIO must be enabled, or USB must be connected.

New application for measuring carbon dioxide (CO2) with mh-z19 sensor

---

applications/Games/color_guess/manifest.yml

- Updated start screen of color guessing game
- None

Leedave/color guess 1.1

---

applications/Games/racso_zero/manifest.yml

- Fixes an issue with a UI popup being stuck in certain situations.
- Adds player icons.
- None

ZERO! v1.3

---

.github/actions/bundle/action.yml
.github/workflows/bundle.yml
tools/bundle.py

Added app build artifacts to PR status

---

.github/workflows/bundle.yml

gh: bundle: Fixed diff logic

---

applications/Sub-GHz/subghz_remote_ofw/manifest.yml

- SubGHz Remote, uses up to 5 .sub files
- No

SubGHz Remote 1.2

---

applications/Games/racso_sokoban/manifest.yml

- Sokoban game for Flipper Zero. Initial release.
- None.

Sokoban 1.0

---

applications/Games/flipperzero_fnaf/manifest.yml

- Changed Back button behaviour. Short presses won't go to main menu while playing anymore.
- No

Five Nights at Flipper's Update 1.1

---

applications/GPIO/fn_test/manifest.yml

Application for testing the fiscal drive (Only for the Russian market): https://kontur.ru/ofd/spravka/401-chto_takoe_fn 
The fiscal drive is connected to the flipper via the UART interface. Connection information is in the Wiring menu of the application
- None

Tester for fiscal drive

---

applications/Games/racso_sokoban/manifest.yml

- Update that fixes an error with certain levels.
- None.

Sokoban 1.1

---

applications/NFC/picopass/manifest.yml

- Fixes compatibility with some readers (Signo) by optimising the crypto to be as fast as all the other commands.
- Unchanged (requires iClass cards or readers to be any use)

Release picopass app v1.4

---

applications/GPIO/esp32_wifi_marauder/manifest.yml

Update wifi marauder app to v0.6.2 to support new gps and wardrive commands

Update wifi marauder app to v0.6.2

---

.github/workflows/bundle.yml
tools/bundle.py

Fixes for release/rc sdk fallbacks

---

applications/GPIO/spi_mem_manager/manifest.yml
applications/NFC/picopass/manifest.yml
applications/Tools/nfc_rfid_detector/manifest.yml

- Picopass, SPI Flash: new random file name API
- NFC/RFID detector: version bump

Picopass, SPI Flash, NFC RFID detector update

---

applications/NFC/seader/manifest.yml

- Bumping to fix random naming include change

Seader: Bump to 1.2

---

applications/Games/sudoku/manifest.yml

New version. Improved board generation algorithm
Nope

Updated Sudoku to v1.1

---

applications/Bluetooth/pc_monitor/manifest.yml

- Add PC Monitor App
- Requires [backend](https://github.com/TheSainEyereg/flipper-pc-monitor-backend) running on user's PC

Add PC Monitor App

---

applications/Sub-GHz/subghz_remote_ofw/manifest.yml

- Sync branches, update to latest version, fix defines
- No

Update SubGHz Remote

---

applications/Games/nupogodi/manifest.yml

- Added more eggs at the same time to make game more complicate
- Increase Flipper level when collect 100 eggs.

Updated nupogodi to v1.2

---

applications/GPIO/camera_suite/manifest.yml

- Update "[ESP32] Camera Suite" application to [v1.3.0](https://github.com/CodyTolene/Flipper-Zero-Camera-Suite/releases/tag/v1.3.0).
- Includes FAP and ESP32-CAM firmware updates.
- Includes a new Flasher Utility for the ESP32-CAM firmware (not part of this software here, but a part of my main repo [here](https://github.com/CodyTolene/Flipper-Zero-Camera-Suite)).
Thanks!

Update Camera Suite application to v1.3.0

---

applications/Games/nupogodi/manifest.yml

Updated nupogodi to v1.2 (new manifest)

---

applications/Infrared/flipper_xremote/manifest.yml

Advanced IR Remote App for Flipper Zero Device
No extra software or hardware required.

Add XRemote IR app

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build.yml
ReadMe.md
documentation/Contributing.md
tools/bundle.py
tools/requirements.txt

- bundler: image handling fixes, updated python dependencies
- gh: build: added checksum to artifact submission; 
- docs: added links to catalog frontends
- fixes #84

Docs & workflow updates

---

applications/Bluetooth/pc_monitor/README.md
applications/GPIO/fn_test/README.md
applications/GPIO/max31855/README.md
applications/GPIO/mh_z19/README.md
applications/GPIO/radar_scanner/README.md
applications/Games/flipperzero_fnaf/README.md
applications/Games/racso_sokoban/README.md
applications/Games/racso_ultimate_tic_tac_toe/README.md
applications/Games/racso_zero/README.md
applications/Games/sudoku/README.md
applications/Infrared/flipper_xremote/README.md
applications/Media/music_player/README.md
applications/Sub-GHz/subghz_remote_ofw/README.md
applications/Tools/clock/README.md

Added missing readmes

---

applications/NFC/seader/manifest.yml

- Remove delay during SAM detection
- Correct save as LFRFID
- update sources glob

Seader: bump version

---

applications/Infrared/flipper_xremote/manifest.yml

- Advanced infrared remote application for flipper device.
- No additional software or hardware is required.

Updated XRemote to v1.1

---

.github/PULL_REQUEST_TEMPLATE.md
.github/actions/bundle/action.yml
.github/workflows/build.yml
.github/workflows/bundle.yml
.github/workflows/widget.yml
ReadMe.md
documentation/Contributing.md
tools/bundle.py
tools/requirements.txt

Updated action dependecies

---

applications/GPIO/radar_scanner/manifest.yml

- Added an alternate pinout mode allowing users to utilize the app with a radar sensor without having to build a custom module
- Reformatted the UI to be cleaner
- Added automatic 5v on GPIO on app enter and auto turn off 5v on app exit
- RCWL-0516 radar sensor
- No more need for other materials

Radar Scanner - V2.0

---

applications/Tools/qrcode/README.md
applications/Tools/qrcode/manifest.yml

- Displays qrcodes on the flipper zero
- n/a

Add qrcode v2

---

applications/NFC/mfkey32/manifest.yml
applications/NFC/nfc_magic/manifest.yml
applications/NFC/picopass/manifest.yml
applications/Tools/nfc_rfid_detector/manifest.yml

- Rework Picopass, Nfc Magic, Nfc Rfid detector, Mfkey32 applications with new NFC API

[FL-3652] Update Good faps manifests

---

applications/Games/hangman/manifest.yml

- Hangman is a guessing game. Flipper thinks of a word and the gamer tries to guess it by suggesting letters within a certain number of guesses.

Hangman game

---

applications/Games/citybloxx/manifest.yml

- This is a new game by me, based on a famous game called City Bloxx where you need to build a tower using blocks. In the future, the main game mode is going to be added, but for now just the "quick game" mode is implemented.
- None

Added City Bloxx

---

applications/GPIO/pokemon/manifest.yml

- Trade refactor
- Add patch list support
- Fix issues with Trainer names
N/A

pokemon: bump to 1.4

---

applications/Games/hangman/manifest.yml

- Hangman is a guessing game. Flipper thinks of a word and the gamer tries to guess it by suggesting letters within a certain number of guesses.

Hangman game was updated

---

applications/Games/citybloxx/README.md
applications/Games/hangman/README.md
applications/Games/questions/README.md
applications/NFC/nfc_magic/manifest.yml
applications/NFC/picopass/manifest.yml
applications/Sub-GHz/weather_station/manifest.yml
applications/USB/mass_storage/manifest.yml

Good-faps for 0.95-rc

---

applications/GPIO/mhz19_uart/README.md
applications/GPIO/mhz19_uart/manifest.yml

- MHZ19 Sensor UART app
- MHZ19 Sensor

Add mhz19 uart app

---

applications/Infrared/xbox_controller/manifest.yml

- Fix build on latest 0.95.0 SDK

Fix Xbox Controller App build on latest 0.95.0 SDK

---

applications/Tools/hex_viewer/manifest.yml

Just pushed my v2.0 version to master-branch, trying to update the app in store
- Massive internal refactoring and new app structure
- "Scroll to ..." menu item which allows you to scroll to any percent of the file

Upgrade to v2.0

---

applications/GPIO/camera_suite/manifest.yml

- Update "[ESP32] Camera Suite" application fap from v1.3 to v1.4.
- Add RC build support and various other code improvements.

Update `Camera Suite` application to v1.4 (RC build & various improvements)

---

applications/Infrared/xremote/manifest.yml

- Updates for app to run in 0.95.0-rc
- none

Updated xremote for 0.95.0-rc compatibility

---

applications/Games/color_guess/manifest.yml

- Color Guessing Game, updated for 0.95.0-rc
- None

Update Color Guess for 0.95.0-rc

---

applications/GPIO/fn_test/manifest.yml

- API 46 support
- noup
- [v] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [v] I own the code I'm submitting or have code owner's permission to submit it
- [v] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

fn_test_0.2 (API 46 support)

---

applications/Games/hangman/manifest.yml

- Hangman is a guessing game. Flipper thinks of a word and the gamer tries to guess it by suggesting letters within a certain number of guesses.

Hangman: fixed building on toolchain 46.0 f7

---

applications/Media/flizzer_tracker/manifest.yml

flizzer tracker: Fix not compiling on newest rc firmware

---

applications/GPIO/esp_flasher/manifest.yml

Fixes build by removing deprecated API calls.

Update ESP flasher to fix build

---

applications/USB/usb_ccb/manifest.yml

- Application for sending USB Consumer Control Buttons as a USB HID device.
- None.

Add manifest.yml for usb_ccb

---

applications/Infrared/xremote/manifest.yml

- Added a setting to control the timing of IR signals (User request)
- none

Added IR Timing setting to Cross Remote

---

applications/Infrared/flipper_xremote/manifest.yml

- Fixed build with latest firmware.

Updated XRemote to v1.2

---

applications/Games/rubiks_cube_scrambler/manifest.yml
applications/Games/tetris/manifest.yml
applications/Media/zero_tracker/manifest.yml
applications/NFC/mifare_fuzzer/manifest.yml
applications/RFID/fuzzer_rfid/manifest.yml
applications/Sub-GHz/pocsag_pager/manifest.yml
applications/Tools/brainfuck/manifest.yml
applications/iButton/fuzzer_ibtn/manifest.yml

- Update 8 apps to work with API v46.x
- :)

New API fixes for 8 apps

---

applications/GPIO/uart_terminal/manifest.yml

- Update manifest to latest commit
- No

Update UART Terminal to latest version

---

applications/Tools/knit_counter/manifest.yml

Sorry, the description formatting was a little unexpected, so I have tried to fix it here.
Thanks for reviewing my submission so quickly!
- None

Fix Knit Counter description

---

applications/NFC/seader/manifest.yml

- "Virtual" card support.  Basically you can select an existing seader .credential file and process the SIO as if it were an real card
- Requires UART to SAM hardware add-on

Seader: v2.1

---

applications/Games/racso_sokoban/manifest.yml
applications/Games/racso_ultimate_tic_tac_toe/manifest.yml
applications/Games/racso_zero/manifest.yml

- Updated 3 apps (Sokoban, ZERO! and Ultimate Tic-Tac-Toe) to fix a compilation error with the latest toolchain versions.
- None.

Updated 3 apps to make them compatible with the latest API versions

---

applications/GPIO/esp_flasher/manifest.yml

v1.4 implements fast flashing (921600 baud) thanks to an espressif library update.

Update ESP flasher to v1.4

---

applications/Games/game_connect_wires/manifest.yml

A puzzle game about rotating differently shaped wires to connect power source with consumers.
No extra requirements

Add Game "Connect Wires"

---

applications/NFC/picopass/manifest.yml

- Save as partial for all read failures
- None

Picopass: update sha for v1.10

---

applications/Media/video_player/manifest.yml

Add Video player app

---

applications/GPIO/esp32_wifi_marauder/manifest.yml

Update wifi marauder app to v0.6.6

---

applications/NFC/nfc_magic/manifest.yml

Update NFC Magic to v1.4

---

applications/NFC/picopass/manifest.yml

Update Picopass to v1.11

---

applications/GPIO/spi_mem_manager/manifest.yml

- SPI Memory Manager updated to v1.3
- None

Update SPI Memory Manager to v1.3

---

documentation/Contributing.md
tools/bundle.py
tools/requirements.txt

* Removed gitpython - https://github.com/gitpython-developers/GitPython/issues/1058 is a blocker
* Now calling git directly

Updated bundler script

---

applications/Tools/smack_my_dolphin_up/manifest.yml

- This application removes .dolphin.state to completely reset dolphin progress.
- No extra requirements

Smack My Dolphin Up! v1.0 added

---

applications/Games/tarot/manifest.yml

- It's a tarot card spread with major arcana cards
- None

Tarot game

---

applications/Tools/tone_gen/manifest.yml

v1
- A simple tone generator application for Flipper Zero devices.
- None

Add Tool "Tone Generator"

---

applications/NFC/nfc_magic/manifest.yml

- Update to latest version.
- None

Nfc Magic: update to latest version

---

applications/GPIO/malveke_gb_live_camera/manifest.yml

- Update to latest version.
- None

Update [MALVEKE] GB Live Camera version 1.2

---

applications/Games/game_vexed/README.md
applications/Games/game_vexed/manifest.yml

Vexed game - remake of Palm.OS Vexed for Flipper Zero

dlvoy/game vexed 1.0.1

---

applications/GPIO/malveke_gb_cartridge/manifest.yml
applications/GPIO/malveke_gb_link_camera/manifest.yml
applications/GPIO/malveke_gb_live_camera/manifest.yml
applications/GPIO/malveke_gb_photo/manifest.yml
applications/GPIO/malveke_gba_cartridge/manifest.yml

- To improve the visibility of the application names, the names were changed by adding a 'MALVEKE' postfix.
- Added **GAME BOY Photo** application
- [MALVEKE PCB](https://www.tindie.com/products/efuentealba/malveke-game-boy-tools-for-flipper-zero/)
- GAME BOY Color / Advance
- Cable Link

Update Malveke Apps manifest

---

applications/Games/color_guess/manifest.yml

Update Color Guess v1.3

---

applications/Infrared/xremote/manifest.yml

Cross Remote v1.1

---

applications/Sub-GHz/weather_station/manifest.yml

Update WS v1.3

---

applications/Games/nupogodi/manifest.yml

- Eggs rolling one by one, not all at the same time
- Back button shows Pause screen, not terminate the game

v1.3: Async eggs; new Pause screen

---

applications/GPIO/malveke_gb_live_camera/manifest.yml
applications/GPIO/pokemon/manifest.yml

- All the application names for GAME BOY/MALVEKE were standardized for better readability on the screen.
- No

Update Pokemon Trading App manifest

---

applications/Games/minesweeper_redux/manifest.yml

The game has a few more features compared to the mine sweeper game that is available right now. It allows you to change the board dimensions (max 32x32) as well as an option to enable an algorithm to verify if a board can be unambiguously solved when a new one is being generated.
I hope that these features are enough to get added to the catalog. I enjoy mine sweeper a lot and its been nice to have a slightly more comprehensive implementation on the flipper.
The application does not require any additional hardware or software.

Added manifest.yml for my Mine Sweeper game.

---

applications/GPIO/mhz19_uart/manifest.yml

- Update mhz19-uart app to latest version(use new serial API)
- None

Update mhz19-uart app to latest version

---

applications/Sub-GHz/weather_station/manifest.yml

- Update weather station
- None

Update weather station

---

applications/NFC/picopass/manifest.yml

- See changelog :grin:
- Access to an iClass card

Picopass: release v1.12

---

applications/Games/minesweeper_redux/manifest.yml

1. Added ability to toggle the led/sound feedback in the settings menu of the game; before users could not disable this and it can be annoying at times
2. Minor bugs fixes with gameplay and user input
3. I restructured a lot of the code to hopefully make it more readable and less nested.
N/A

Update to minesweeper game

---

applications/NFC/mfc_editor/manifest.yml

- Editor and viewer for MIFARE Classic .nfc files
- Supports editing raw block content as well as special edit views for things like UID, Keys, and Access Conditions
- None

MIFARE Classic Editor

---

applications/GPIO/camera_suite/manifest.yml

- Update "[ESP32] Camera Suite" application fap from v1.5 to v1.6.
Tons of good updates! Changelog here: 
https://github.com/CodyTolene/Flipper-Zero-Camera-Suite/releases/tag/v1.6.0
Thank you

Update "Camera Suite" application to v1.6

---

applications/Games/flipperzero_fnaf/manifest.yml

- Fixed images (two of them were 65px in height) for the new SDK.
- No

Five Nights at Flipper's 1.2 update

---

applications/USB/bc_scanner/manifest.yml

- bc_scanner SDK 0.98.1 support (resolve https://github.com/polarikus/flipper-zero_bc_scanner_emulator/issues/8)
- none

bc_scanner  SDK 0.98.1 support

---

applications/NFC/seader/manifest.yml

Seader: v2.4

---

applications/Infrared/xremote/manifest.yml

Updated Cross Remote to v2.3

---

applications/GPIO/esp32_wifi_marauder/manifest.yml

Adds unified serial feature and fixes for new serial API

Update marauder app to v0.7.0

---

applications/GPIO/esp_flasher/manifest.yml

Fixes the app to build with the new API

Update ESP Flasher to v1.5

---

applications/Infrared/xremote/manifest.yml

- Add support for encoded SubGhz Files
- Added default timer setting for encoded SubGhz Files
- Added version number to app info screen
- Minor readme updates

Cross Remote 2.4

---

applications/GPIO/air_mouse/manifest.yml

- App renamed: Air Mouse -> BMI Air Mouse
-

BMI160 Air Mouse app rename

---

applications/Tools/video_game_module_tool/README.md
applications/Tools/video_game_module_tool/manifest.yml

- Video Game Module Tool - a standalone firmware updater/installer for the Video Game Module
- Requires: Video Game Module

Add video game module tool

---

applications/GPIO/vgm_air_mouse/README.md
applications/GPIO/vgm_air_mouse/manifest.yml

VGM Air Mouse app

---

applications/Games/air_arkanoid/README.md
applications/Games/air_arkanoid/manifest.yml

Air Arkanoid game

---

applications/GPIO/vgm_air_mouse/manifest.yml
applications/Games/air_arkanoid/manifest.yml
applications/Tools/video_game_module_tool/manifest.yml

- Added readmes and changelogs to VGM apps
- Nothing

VGM apps: descriptions fix

---

applications/GPIO/unitemp/manifest.yml

Update Unitemp to 1.4

---

applications/Games/minesweeper_redux/manifest.yml

Fixed LED bug on game loss/win.
Fixed start screen bug with back button input.

Bug fixes for minesweeper redux game.

---

applications/Tools/financial_calc/manifest.yml

- A simple financial calculator to solve TVM problems
- none

financial_calc_1.0

---

applications/Tools/techart_calendar/manifest.yml

Simple Calendar App for Flipper Zero
- **Monthly View:** Display the days of the current month.
- **Navigation:** 
- **Left Button:** Move to the previous month.
- **Right Button:** Move to the next month.
- **Top Button:** Move to the next year.
- **Bottom Button:** Move to the previous year.

Calendar application v1.0

---

applications/Tools/video_game_module_tool/manifest.yml

- Update VGM to version 1.2
- None

[FL-3773] Update Video Game Module Tool

---

applications/Media/video_player/manifest.yml

- Added volume control (up/down arrow keys)

Update Video player app

---

applications/Games/air_labyrinth/README.md
applications/Games/air_labyrinth/manifest.yml

- This is version 0.1 of the Air Labyrinth game.  In this version, you move a ~ character around a maze.  This uses the Video Game Engine and supports input from both the d-pad or the Video Game Module.  The player character is really small, so it is recommended to use HDMI output.   The v0.1 has printing on the edges of the game; but in the future the intent is to add a start screen instead.
- The game leverages the Video Game Engine.  It is recommended to have the Video Game Module for both motion and video output to larger screen, but it is not required.

Jamisonderek/air labyrinth 0.1

---

applications/Tools/dcf77_clock_sync/manifest.yml

- Fixed incompatibility with old firmware

DCF77 Clock Sync Release 1.1

---

applications/Tools/clock/manifest.yml

- Clock: update to latest version
- None

Clock: update to latest version

---

applications/GPIO/avr_isp/manifest.yml

- AVR_ISP: Update version 1.1
- Run and check the functionality of the application

AVR_ISP: Update version 1.2

---

applications/Games/color_guess/manifest.yml

- I've applied changes to make the app run in 0.99.0-rc and later (it will not compile with ufbt on lower versions, as the libraries new are only available in the new release and the old libraries are only available in the old release -> note a deprecation phase would have made things work better)

Update for 0.99.0-rc

---

applications/GPIO/vgm_air_mouse/manifest.yml

- Air Mouse app update to support new BLE profile system
-

Air Mouse: new BLE profile

---

applications/Sub-GHz/weather_station/manifest.yml

- WS: Update version 1.5
- Run and check the functionality of the application

WS: Update version 1.5

---

applications/NFC/nfc_magic/manifest.yml
applications/NFC/picopass/manifest.yml

- Update nfc magic
- Update picopass
-

Update nfc magic and picopass

---

applications/Games/doom/manifest.yml
applications/Games/game_2048/manifest.yml
applications/Tools/analog_clock/manifest.yml
applications/Tools/dcf77/manifest.yml

- Updated 4 apps for latest API (datetime lib and new gcc12)
- :)

Update 4 apps to latest API

---

applications/GPIO/air_mouse/manifest.yml

Existing app, update for new SDK.

Update BMI Air Mouse for 0.99.0-rc

---

applications/GPIO/malveke_gb_cartridge/manifest.yml
applications/GPIO/malveke_gb_link_camera/manifest.yml
applications/GPIO/malveke_gb_live_camera/manifest.yml
applications/GPIO/malveke_gb_photo/manifest.yml
applications/GPIO/malveke_gba_cartridge/manifest.yml

- Implement new serial API with new module expansion protocol.
- [MALVEKE PCB](https://www.tindie.com/products/efuentealba/malveke-game-boy-tools-for-flipper-zero/)
- GAME BOY Color / Advance
- Cable Link

Update MALVEKE Apps manifest 2.0 

---

applications/GPIO/camera_suite/manifest.yml

- Update "[ESP32] Camera Suite" application fap from v1.6 to v1.7:
- Support Flipper Zero Firmware v0.98-rc+ UART updates.
- Full changelog: https://github.com/CodyTolene/Flipper-Zero-Camera-Suite/releases/tag/v1.7.0

Update "Camera Suite" application to v1.7

---

applications/NFC/seader/manifest.yml

- update for bit_lib.h move
- Read and save SAM serial number to file for future work

Seader: v2.5

---

applications/Tools/calculator/manifest.yml
applications/Tools/programmercalc/manifest.yml

- Programmer Calculator - Initial release v0.9
- This version marks its initial release, bringing various number system conversions crucial for embedded systems development, debugging, and digital electronics design.
- Features
- Decimal to Binary conversion
- Decimal to Hexadecimal conversion
- Decimal to Character display
- Hexadecimal to Binary conversion
- Hexadecimal to Decimal conversion
- Binary to Decimal conversion
- Binary to Hexadecimal conversion
- No extra hardware is required to run this application on Flipper Zero devices.

Armixz/programmercalc 0.9

---

applications/Tools/quac/manifest.yml

- A QUick ACtion remote control app that lets you send saved signals of varying types. After recording signals using the existing firmware applications, which are then saved on the SD card, users will re-organize those files into the `/ext/apps_data/quac` folder to generate the app's UI. This lets users logically group actions, even though they may be of different types. For example, you could create a "Work" group/folder which contains a sub-ghz signal for the parking gate, and a rfid signal for opening the parking structure door. Users no longer need to perform lengthy navigation to each ap to find their saved signals.
- Does not require extra hardware or software

Adding Quac!

---

applications/GPIO/malveke_gb_cartridge/manifest.yml
applications/GPIO/malveke_gb_link_camera/manifest.yml
applications/GPIO/malveke_gb_live_camera/manifest.yml
applications/GPIO/malveke_gb_photo/manifest.yml
applications/GPIO/malveke_gba_cartridge/manifest.yml

- Fix FuriHalRtc: new datetime lib
- [MALVEKE PCB](https://www.tindie.com/products/efuentealba/malveke-game-boy-tools-for-flipper-zero/)
- GAME BOY Color / Advance
- Cable Link

Update MALVEKE Apps manifest 2.1

---

applications/GPIO/esp32_wifi_marauder/manifest.yml

Bug fixes and improvements, and changes to make it compile for new toolchain

Update wifi marauder app to v0.7.1

---

applications/Tools/dcf77_clock_sync/manifest.yml

- Updated for the DateTime changes in the latest API
- Use Locale to format Date and Time
- This version is only compatible with the latest Release 0.99.1

Update DCF77 Clock Sync to v1.3

---

applications/Infrared/flipper_xremote/manifest.yml

- Implemented alternative names functionality
- Implemented case-insensitive button search
- Added Eject button support
- Fixed bugs and refactored code
- No extra requireents

Updated XRemote to v1.3

---

applications/Games/flippy_road/manifest.yml

- A simple arcade game for the Flipper
- N/A

Add Flippy Road game

---

applications/Games/flipper_hero/README.md
applications/Games/flipper_hero/manifest.yml

Flipper Hero is a typing game that challenges you to improve your typing skills by inputting codes. Track your score and challenge yourself to beat it with each attempt.
- N/A
Video 
https://www.reddit.com/r/flipperzero/comments/1blydyo/i_recreated_the_stratagem_hero_from_helldivers_2/

Add flipper-hero game

---

applications/Bluetooth/findmy/manifest.yml

- Added Tile Tracker support
- Fixed a couple small bugs
- Tag Type now saves to file
- Computer or AirTag

Update findmy @ V2.0

---

applications/Games/rock_paper_scissors/manifest.yml

- Version 1.5 of Rock Paper Scissors.  Same game features as previous version, but with updated APIs due to changes in DateTime.
- Multi-player game, so it requires two Flippers.

rock_paper_scissors version 1.5

---

applications/GPIO/avr_isp/manifest.yml

- AVR_ISP: Update version 1.3
- Launch the application and check functionality

AVR_ISP: Update version 1.3

---

applications/Media/flizzer_tracker/manifest.yml

Flizzer Tracker v0.6

---

applications/Games/sudoku/manifest.yml

tested on sdk versions 0.99.1 and 21e7c460

Update sudoku to support new sdk

---

applications/Games/questions/manifest.yml

- Fix failing build on SDK 0.99 and 0.100

Update Questions to v1.1

---

applications/Games/flipper_hero/manifest.yml

- Fix error with wrong scores on start
- Make better logos
- Made build on 0.25 KB  (3%) smaller
- N/A
| Before                | After                 |
|-----------------------|-----------------------|
| ![Before](https://github.com/flipperdevices/flipper-application-catalog/assets/50594730/316c3318-30f2-492c-a2a4-9c562f09403a) | ![After](https://github.com/flipperdevices/flipper-application-catalog/assets/50594730/0188ec8b-7e66-4a7d-af07-2803b8fefa4f) |

Update flipper hero to v1.2

---

applications/Media/flizzer_tracker/manifest.yml

Flizzer Tracker small fixes

---

applications/Games/matagotchi/README.md
applications/Games/matagotchi/manifest.yml

Matagotchi by MrModd
- A Tamagotchi(R) like game for Flipper Zero
- This application has no extra requirements.

Added Matagotchi 1.0

---

applications/Media/dvd_screensaver/manifest.yml

- A clone of the iconic DVD screensaver for the FZ.
- None

add dvd_screensaver

---

applications/Bluetooth/findmy/manifest.yml

- Added the ability to toggle showing MAC address on menu screen
- Fixed some issues with saving files and added backwards compatibility for show MAC setting
- UI changes for menu
- An Airtag, Samsung Tag, or Tile Tag as before

Update findmy to V3

---

applications/GPIO/malveke_gb_cartridge/manifest.yml
applications/GPIO/malveke_gb_photo/manifest.yml
applications/GPIO/malveke_gba_cartridge/manifest.yml

- Fix [UART transfer data error](https://github.com/flipperdevices/flipperzero-firmware/issues/3531) (gcc optimization) 
- Fix [Parse Error in GB and GBA apps](https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/issues/31) 
- Fix Frozen upon exiting the gb photo.
- [MALVEKE PCB](https://www.tindie.com/products/efuentealba/malveke-game-boy-tools-for-flipper-zero/)
- GAME BOY Color / Advance

Update MALVEKE Apps manifest 2.2

---

applications/NFC/nfc_magic/manifest.yml

Update NFC Magic

---

applications/Bluetooth/bt_trigger/manifest.yml
applications/GPIO/flipper_geiger/manifest.yml
applications/Games/heap_defence/manifest.yml
applications/Media/text2sam/manifest.yml
applications/Tools/pomodoro_timer/manifest.yml

- Fixed apps for newest API
- 😎

Fix multiple apps for API 60.x

---

applications/Sub-GHz/weather_station/manifest.yml

- WS: update version 1.6, add Acurite 5n1 protocol
- Launch and check reception, directly with the device or from a recorded RAW
[RAW_weather_station.sub.txt](https://github.com/flipperdevices/flipper-application-catalog/files/14863392/RAW_weather_station.sub.txt)

WS: update version 1.6, add Acurite 5n1 protocol

---

applications/Infrared/xremote/manifest.yml

- Fix for crashes on exit on fw 0.100.3

Cross Remote release 2.5

---

applications/GPIO/noptel_lrf_sampler/manifest.yml

Added Noptel LRF rangefinder sampler app manifest

---

applications/Games/game_connect_wires/manifest.yml

A puzzle game about rotating differently shaped wires to connect power source with consumers.
Update to 1.1 - bug fixes and improvements (now can switch rotation direction)
No extrarequirements

Update game Connect Wires to 1.1

---

applications/Games/game_connect_wires/manifest.yml

Small memory leak fix
No extra requirements

Update game_connect_wires to 1.2

---

applications/GPIO/fn_test/manifest.yml

SDK 1.0.0 support (API 60.4)

---

applications/Tools/quac/manifest.yml

Added IR and NFC support
Action settings to: Rename, Delete, Import, Create Group
Support for External Sub-GHz antenna
About screen

Updating Quac! to v0.6

---

applications/Sub-GHz/weather_station/manifest.yml

- Ws: update version 1.7
- Insert the external CC1101, launch the application, select the external module and check the reception of weather stations

Ws: update version 1.7

---

applications/Tools/flipperzero_clock/README.md
applications/Tools/flipperzero_clock/manifest.yml

- FlipperZero customizable clock with digital and analog faces

Added FlipperZero Customizable Clock

---

applications/GPIO/malveke_gb_photo/manifest.yml

- Memory optimization and fix for issue [#35.](https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/issues/35)
- [GAME BOY Camera RAM](https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/files/14892495/GAMEBOYCAMERA_0.zip) (.sav)

Update malveke_gb_photo 2.3

---

applications/Infrared/mitsubishi_ac_remote/manifest.yml

Add Mitsubishi AC Remote

---

applications/Media/flizzer_tracker/manifest.yml

Flizzer Tracker update

---

applications/GPIO/noptel_lrf_sampler/manifest.yml

New in version 1.4:
- Added automatic SMM sampling mode
- Sampling buffer sizeable by number of samples as well as time
- Added buffering indicator
- Added return rate indicator
- Save diagnostic data files in a dedicated folder

Updated noptel_lrf_sampler to 1.4

---

applications/NFC/nfc_magic/manifest.yml

- Nfc Magic update to 1.9 version

NfcMagic update to 1.9 version

---

applications/Games/minesweeper_redux/manifest.yml

Bug fixes and QOL updates.
Gain flipper XP.
N/A

Update minesweeper_redux game v1.4

---

applications/Games/flight_assault/manifest.yml

- [Flight Assault is a dynamic action game for flipperzero where players control a spacecraft engaged in combat against enemy ships approaching from different directions ]
- [ None ]
- [X ] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [ X] I own the code I'm submitting or have code owner's permission to submit it
- [X ] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

Initial version

---

applications/Games/game_hanoi_towers/manifest.yml

- A simple puzzle game which is about moving a tower of disks onto another stick. Player can only put smaller disks on bigger ones. There are only 3 stitcks and the the task is to move the entire tower to any other one.
- No extra requirements

Added a game - Hanoi Towers

---

applications/NFC/picopass/manifest.yml

- First release in new repo: https://gitlab.com/bettse/picopass
- adds wiegand plugin
- saves unknown blocks using `??`
- None

Picopass 1.14

---

applications/Games/flight_assault/manifest.yml

Flight Assault Version 0.2

---

applications/NFC/seader/manifest.yml

- Added MFC SE support
- Added plugin to parse wiegand

Seader: v2.8

---

applications/Tools/techart_calendar/manifest.yml

Update manifest.yml of calendar app

---

applications/Games/flight_assault/manifest.yml

- [ 0.3 - Added bonus lives feature to the game ]
- [ None ]

Evillero/flight assault 0.3

---

applications/NFC/picopass/manifest.yml

- Added "save as legacy" for iClass SR (corrects the first byte of the pacs configuration block)
- none

Picopass v1.5

---

applications/GPIO/flipagotchi/manifest.yml

- Fixed broken description from last submission
- No new requirements

Fix broken description

---

applications/Games/color_guess/manifest.yml

- Update of Color Guess to version 1.5
- Improved Memory Management
- Fix redraw issue for launches outside of menu
- Added version number to Startscreen
- Added GNU License

Color Guess 1.5

---

applications/NFC/nfc_magic/manifest.yml

Update NFC Magic to v1.10

---

applications/Tools/flipbip/manifest.yml

- FlipBIP Crypto Wallet
- Updated to support new firmware

FlipBIP 1.15

---

applications/Games/chess/manifest.yml

- Chess
- Updated to support new firmware

Chess 1.10

---

applications/GPIO/magspoof/manifest.yml

- GUI fixes
- Additional settings: repeat mode
- Repeated emulation logic
- Misc cleanup
- Cf. original PR adding the app #375

Update MagSpoof to v0.10

---

applications/Tools/flipbip/manifest.yml

- FlipBIP v1.16
- Minor UI changes/cleanup

FlipBIP 1.16

---

applications/Games/racso_sokoban/manifest.yml

- Sokoban: fixed compilation error on the latest SDK version.
- None.

Sokoban 1.3

---

applications/GPIO/pokemon/manifest.yml

v2.0:
- Adds support for Generation II games, w/ custom sprite art
-  Fixes MALVEKE breaking OK button during trade
Needs Game Boy + pokemon game

GPIO/pokemon: bump to 2.0

---

applications/GPIO/flipboard_simon/manifest.yml

- This application turns the FlipBoard MacroPad into a memory game!  Try to remember and repeat the sequence of lights and sounds on the FlipBoard!
- See https://youtu.be/7U9VUhN4e2w?t=1488 for demo of playing an older version of the game.
- I recommend the FlipBoard, but if you want to make something similar... use 4 WS2812B LEDs connected in a chain, with the data-in of the first LED going to PC3.  The switches are on PA6, PA4, PB3, PB2.  The status LED is on PA7.

FlipBoard Simon v1.9

---

applications/GPIO/simultaneous_rfid_reader/manifest.yml

- This app is designed to work with the M6e Nano UHF RFID Reader and the Flipper Zero. This app supports reading up to 150 tags per second, writing to tags (EPC, TID, Reserved, and User Memory Banks), viewing all tag information, saving tags, and more!
Here is a video with a demo for the [app](https://drive.google.com/file/d/1fJ3wJB3fZCRJra3UQ8qU64asjypHBqOc/view?usp=sharing). 
Please see my [README](https://github.com/haffnerriley/Simultaneous-UHF-RFID-FlipperZero/blob/main/README.md) for a better description with links and screenshots included! 
Currently, this Flipper Zero application requires an [M6e Nano](https://www.jadaktech.com/product/thingmagic-m6e-nano-uhf-rain-rfid/) compatible UHF RFID Reader. I recommend one of the following options:
- [SparkFun Simultaneous RFID …

Simultaneous_uhf_rfid_reader_1.0

---

applications/Media/dvd_screensaver/manifest.yml

- Logo now starts at a random position with a random direction.
- None

dvd_screensaver - update to 1.1

---

applications/GPIO/flipboard_keyboard/manifest.yml

- Version 3.8 fixes the case where Keystroke selector not rendering all buttons.
Repo steps: launch app, choose "Configure application", choose "Action 1", scroll down to "Keystroke" option, click "OK", click down button on Flipper 4 times.  Some of the top row of displayed keys were shown as empty squares.
- I recommend the FlipBoard, but if you want to make something similar... use 4 WS2812B LEDs connected in a chain, with the data-in of the first LED going to PC3.  The switches are on PA6, …

FlipBoard Keyboard v3.8

---

applications/GPIO/air_mouse/manifest.yml

This adds support for LSM6DS3 and LSM6DSO IMUs.
Updating existing application
Extra hardware needed, see README.md

Update BMI Air Mouse

---

applications/Games/flipperzero_fnaf/manifest.yml

Fix a bug that appeared on latest firmwares. Change description.
None

Five Nights at Flippers 1.3 update

---

applications/GPIO/unitemp/manifest.yml

- Unitemp 1.5 update - Dependencies fixed
- not required

Unitemp 1.5 update

---

applications/GPIO/zeitraffer/README.md
applications/GPIO/zeitraffer/manifest.yml

- Simple timelapse/intervalometer app for Flipper Zero, works via GPIO pins 6 and 7. 
- Cable with optocouplers. Assebmly instruction in readme.

Theageoflove/zeitraffer 1.2

---

applications/Media/music_player/manifest.yml

- music_player: Update version 1.2
- music_player: Update version 1.3

music_player: Update version 1.3

---

applications/Tools/clock/manifest.yml

Clock: Update version 1.2

---

applications/NFC/nfc_magic/manifest.yml

- Update application to 1.11
- Magic cards

Nfc Magic: update application

---

applications/NFC/mfkey/README.md
applications/NFC/mfkey/manifest.yml

re-added mfkey v2.5

---

applications/NFC/mfkey/manifest.yml

version bump for workflow test
-

mfkey v2.6

---

applications/Games/dice_app/manifest.yml

- Dice app: Update the app for the SDK version 0.103 f7.
- No any extra hardware or software requires.

Dice D&D app: Update to version 1.3

---

applications/Tools/tasks/manifest.yml

[FlipperTasks](https://github.com/MadLadSquad/FlipperTasks) is a simple to-do list application. It has everything a user expects from a functional to-do list app:
1. Tasks have display names and long descriptions, which can all be edited
1. Tasks can be marked as done, not finished and deleted
1. The user can view and edit completed tasks
1. Data is saved on-device(on the SD card) in the form of human-readable text files
None

NEW FAP: Flipper Tasks 1.0

---

applications/Tools/nfc_rfid_detector/manifest.yml

- Nfc_Rfid_detector: update version 1.3

Nfc_Rfid_detector: update version 1.3

---

applications/NFC/picopass/manifest.yml

- Acknowlegements
- Elite VB6 RNG keygen attack
- none

Picopass v1.6

---

applications/Tools/qrcode/manifest.yml

- Displays qrcodes on the flipper zero. This version merely updates the code to fix some build errors with firmware v0.103.x.
- n/a

qrcode v2.1

---

applications/NFC/seader/manifest.yml

- Bumped wiegand plugin version to add more format support
- Added handling of SAM being removed on main screen
- Requires uart to sam interface ("nard") and a HID SAM

Seader 2.9

---

applications/Infrared/ir_intervalometer/manifest.yml

Fixes compile issues
- Fixes callback signature changed in new Flipper SDK version
- None

Bump IR Intervalometer Version to 0.2.2

---

applications/GPIO/camera_suite/manifest.yml

- Update "[ESP32] Camera Suite" application fap from v1.7 to v1.8.
- Changelog:
- Use new Flipper Zero "DateTime" type for image filenames as "YYYYMMDD-HHMMSS.bmp".
- Fix pinout guide image in-app for "GND-GND" pin reference. Thanks PyroJoe313!
- Fix up horizontal flip when camera is rotated 180 degrees. Thanks 4k3or3et!

Update "Camera Suite" application to v1.8

---

applications/Games/jetpack_game/manifest.yml

- Updated jetpack_game to SDK 0.103
- none

Updated jetpack_game to SDK 0.103

---

applications/Games/minesweeper_redux/manifest.yml

QOL updates and wrap around on move added
N/A

Update Minesweeper Redux to v1.5

---

applications/Games/racso_sokoban/manifest.yml

- Sokoban updated to version 1.4: improved board drawing, UX improvements.
- N/A

Sokoban 1.4

---

applications/NFC/seader/manifest.yml

- Nothing significant, but lots of small tweaks in preparation for T=1 and APDU Runner support coming later.

Seader v2.10

---

applications/GPIO/flipboard_signal/manifest.yml
applications/Sub-GHz/fmf_to_sub/manifest.yml

- This version contains improvements so that multiple buttons on the FlipBoard can be pressed at the same time and an associated signal will be sent.  The button values [1], [2], [4] and [8] are combined to determine the signal to send.  For example, pressing leftmost and rightmost buttons at same time will send Flip9.sub and Flip9 codes from the flipboard.ir file.
- This application requires a FlipBoard or compatible device.

Jamisonderek/flipboard signal 3.12

---

applications/Tools/key_copier/manifest.yml

- This app helps users measure physical keys by drawing a contour template while placing their key on top of the Flipper Zero screen.
- This app support Kwikset KW1 and Schalge SC4 format keys. The format can be selected in the Config menu. 
- The bitting numbers for each pin is controlled by user input. The resulting contour is calculated based on actual key specs from data sheets.
- The measurements can be saved and loaded for later use. The app comes with its custom .keycopy file extension and the corresponding Flipper Format.  
- No extra hardware or software needed.

New App: Key Copier v1.0

---

applications/Sub-GHz/fmf_to_sub/manifest.yml

- This version handles short pauses (like 32nd not pauses)
- This version plays the duration of each tone more accurately
- No hardware is required.

fmf_to_sub 1.2

---

applications/GPIO/flipperscope/manifest.yml

- Fixed compilation issue
- Uses GPIO pins

Bump flipperscope to v0.3

---

applications/Tools/knit_counter/manifest.yml

- Fixes build failure https://github.com/fridgepoet/knit-counter/issues/6

Update Knit Counter version to fix build failure

---

applications/Games/chess/manifest.yml

- Chess
- Updated to support new firmware
- N/A

Chess 1.11

---

applications/Tools/flipperzero_clock/manifest.yml

- FlipperZero Customizable Clock

Bump flipperzero clock to v1.2

---

applications/NFC/seader/manifest.yml

- Fixes support for firmware v0.105.0
- Adds T=1 support
- Adds APDU Runner

Seader v3.0

---

applications/Games/eightball/README.md
applications/Games/eightball/manifest.yml

This new app is a simple implementation of the classic Magic 8-ball game for the flipper zero.
There are no extra hardware or software requirements.

New App: eightball

---

applications/Media/flizzer_tracker/manifest.yml

- Fix app not reacting to keypresses on most recent firmware version due to the app's poor handling of view dispatcher

Update Flizzer Tracker

---

tools/requirements.txt

tools: synced Python deps versions

---

applications/GPIO/esp_flasher/manifest.yml

No functional changes, just fixed recent toolchain errors by fixing cdefines in application.fam.

Update ESP flasher to v1.6

---

applications/Infrared/xremote/manifest.yml

- Updated application to use the new number_input keyboard instead of the now removed custom made keyboard
- Firmware must be at least on 0.105.0, older no longer supported

Update Cross Remote v2.7

---

applications/NFC/seader/manifest.yml

- Fixed key calculation with "Save as SR"

Seader v3.1

---

applications/NFC/picopass/manifest.yml

- CVE-2024-41566: When keys are unknown, emulate with a dummy MAC and ignore reader MACs
- none

Picopass v1.17

---

applications/Games/laser_tag/manifest.yml

Laser Tag v1.0

---

applications/Games/laser_tag/manifest.yml

Laser Tag v1.1

---

applications/Tools/tasks/manifest.yml

Flipper Tasks v1.1

---

documentation/Manifest.md

Hi, how are you?
Just wanna share a tiny typo that I found on the manifest.md
Also, I delete the trailing spaces.

fix(typo): Fix really tiny typo on manifest

---

applications/Tools/upython/manifest.yml

* Added simple GPIO support: initialize, read, write, interrupts.
* Added constants for musical note frequencies from C0 up to B8.
* Some minor fixes in the dialog functions.

Bump uPython version to 1.2

---

applications/Games/laser_tag/manifest.yml

Add RFID Powerups by @jamisonderek 
Add External IR Board support by @RocketGod-git 
None

Laser Tag v2.0

---

applications/Tools/rot13_app/manifest.yml

- [ I created a simple app that will take a text an convert that text using rot13. ]
- [ Does not require extra hardware ]
Gonna add the screenshot of the validation:

feat(Tools): Add new rot13 app

---

applications/Tools/upython/manifest.yml

* Added simple ADC support for the `flipperzero` module:
* Read raw value.
* Read voltage.
* Added simple PWM support for the `flipperzero` module:
* Start a signal.
* Stop a signal.
* Check the status.
* Added infrared support for the `flipperzero` module:
* Receive a signal.
* Transmit a signal.
* Check the status.
* Reset used GPIO pins upon script termination.
* Improved GPIO related functions to prevent user errors.
* Published [Python package on PyPI](https://pypi.org/project/flipperzero/) for code completion support.

Update uPython to version 1.3

---

applications/Games/roots_of_life/manifest.yml
applications/Sub-GHz/subghz_remote_ofw/manifest.yml

- Update SubGHz Remote and Roots of Life
- No

Update SubGHz Remote and Roots of Life

---

documentation/Contributing.md

docs: updated contribution guide

---

applications/NFC/cyborg_detector/manifest.yml

App generates a continous NFC field to make body mod implant LEDs glow. Tested on a Dangerous Things xSIID.
None
None

Cyborg Detector v1.0

---

applications/Games/laser_tag/manifest.yml

Flipper Application Catalog layout changes
None

Laser Tag v2.1

---

applications/GPIO/air_mouse/manifest.yml
applications/GPIO/avr_isp/manifest.yml
applications/GPIO/dap_link/manifest.yml
applications/GPIO/signal_generator/manifest.yml
applications/GPIO/spi_mem_manager/manifest.yml
applications/GPIO/vgm_air_mouse/manifest.yml
applications/NFC/nfc_magic/manifest.yml
applications/Sub-GHz/weather_station/manifest.yml
applications/Tools/nfc_rfid_detector/manifest.yml
applications/Tools/video_game_module_tool/manifest.yml
applications/USB/mass_storage/manifest.yml

Update good faps (https://github.com/flipperdevices/flipperzero-good-faps) to their latest versions

Update good faps

---

applications/Games/lifecounter/manifest.yml

- Life tracker for collectible card games such as Flesh and Blood, Magic the Gathering, Sorcery, Lorcana etc.
- None

Lifecounter v1.0

---

applications/NFC/cyborg_detector/manifest.yml

App Catalog improvements.
None

Cyborg Detector v1.1

---

applications/Games/laser_tag/manifest.yml

Laser Tag v2.2

---

applications/GPIO/flipper_gb_printer/README.md
applications/GPIO/flipper_gb_printer/manifest.yml

Initial commit of v0.1 code
Emulates a Game Boy Printer to receive print data from a Game Boy and save the data as a PNG image.
Game Boy Link Cable interface to Game Boy, Game Boy, and a Game Boy game with printing support.

GPIO: flipper_gb_printer: Initial commit

---

applications/Games/laser_tag/manifest.yml

- Fix thread leak by CodeAllNight (@jamisonderek)
- Fix crash when fire is sent while hit is processing by RocketGod (@RocketGod-git)
None

Laser Tag v2.3

---

applications/Sub-GHz/radio_scanner/manifest.yml

Sub-GHz radio scanner with output to internal speaker
None

Radio Scanner v0.2

---

applications/Tools/flipper95/README.md
applications/Tools/flipper95/manifest.yml

Application to stress test the Flipper by finding Mersenne primes using the Lucas-Lehmer Test, much like Prime95 does.
None.

Added Flipper95

---

applications/Tools/flipbip/manifest.yml

Update FlipBIP to v1.17

---

applications/NFC/seader/manifest.yml

- T=1 support (should feel faster when taking to a card)

Seader v3.2

---

applications/Games/umpire_indicator/manifest.yml

A baseball umpire indicator app for the Flipper Zero device! This app simulates a traditional baseball umpire's counter, tracking balls, strikes, and outs with a classic scoreboard-style interface.
None

Umpire Indicator v0.1

---

applications/Games/flight_assault/manifest.yml

Initial checkin

---

applications/Tools/fast_js_app/manifest.yml

- FastJS allows users to pre-save their selected JavaScript files for quick execution. Since users can't currently set scripts to Favorite App or Dummy Mode buttons, they can favorite FastJS instead. In the configuration view, users can choose which script to save and opt for FastJS to remember their selection. Utilizing the storage library, FastJS securely saves user preferences for seamless access. Thank you for taking the time to review this app!
- N/A

FastJS v1.0

---

applications/Tools/fast_js_app/manifest.yml

- Updated the File Browser to open in the Apps/Scripts folder
- N/A

FastJS v1.01

---

example/manifest.yml

This PR contains small fixes and improvements to the manifest sample.

Fix typos in manifest.yml

---

applications/Tools/trackerflipx/manifest.yml

Flipper Time Tracker is an application for flipperzero device that allows the user to track multiple tasks at the same time.
- no extra reqs (free space for the csv file)

Massiv dash/trackerflipx 1.0.2

---

applications/Tools/upython/manifest.yml

- Allow passing the path to the script to execute as a CLI argument.
- Open a REPL from the CLI interface by using the `py` command.
- MicroPython update to version 1.23.0.
- [MicroPython](https://github.com/micropython/micropython) is bundled with the application

Update uPython to 1.4

---

applications/GPIO/web_crawler/manifest.yml

- Updated the progress messages displayed after sending a GET request.
- Renamed the "Config" main submenu option to "Settings."
- Added a submenu (WiFi, File, Request) that appears when users click the "Settings" option.
Clicking **WiFi** displays a variable item list for SSID and Password. If you click:
- **SSID**: A text input screen will appear with the current saved SSID pre-filled. You can change the SSID by editing the text and clicking "Save."
- **Password**: A text input screen will appear with the current saved password pre-filled. You can change the password by editing the text and clicking "Save."
Clicking **File** displays a variable item list with options to Read File, Set File …

Update Web Crawler to v0.3

---

applications/GPIO/web_crawler/manifest.yml

- Updated the text input to match the text input from the UART Terminal app (big thanks to xMasterx)
- Added POST and PUT requests (with payloads)
- Added headers
- Added more error handling
- WiFi Dev Board for Flipper Zero with FlipperHTTP Flash: https://github.com/jblanked/WebCrawler-FlipperZero/tree/main/assets/FlipperHTTP
- WiFi Access Point

Update Web Crawler to 0.4

---

applications/Tools/upython/manifest.yml

- Support for basic file system operations using the `io` module.
- Simple `logging` module for level based log messages.
- Output redirection of `print` statements, based on script invocation.
- UART support for the `flipperzero` module.
- The `py` command waits now until the script terminates.
- Fixed `CR` and `LF` handling in the REPL.
- [MicroPython](https://github.com/micropython/micropython) is bundled with the application.

Update uPython to 1.5

---

applications/GPIO/eth_troubleshooter/README.md
applications/GPIO/eth_troubleshooter/manifest.yml
applications/Sub-GHz/esubghz_chat/README.md
applications/Sub-GHz/esubghz_chat/manifest.yml

- eth_troubleshooter
- esubghz_chat
- eth_troubleshooter works with external module, basic testing can be done without module
- esubghz_chat works with internal and external cc1101, can be tested without extra hardware, requires second flipper

Add two apps

---

applications/NFC/mfkey/manifest.yml

- Added Static Encrypted Nested key recovery, added NFC app support, dropped FlipperNested support
- N/A

Bump MFKey version to v3.0

---

applications/Tools/lishi/manifest.yml

- [ Updated application name 
-  Added a new menu for easier navigation
-Added different types of lishi ]
- [ Lishi Tool ]
- [ X] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [ X] I own the code I'm submitting or have code owner's permission to submit it
- [X ] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

Version 0.2

---

applications/Games/banana/manifest.yml

- Added menu
- Added about in the menu
- Fixed animation
- none

Update Banana v0.4

---

applications/NFC/nfc_maker/README.md
applications/NFC/nfc_maker/manifest.yml

- Creates NDEF formatted NFC files for BT MACs, Contacts, Links, Emails, Phones, Text and WiFis
- None

Add NFC Maker v1.2

---

applications/GPIO/flip_library/manifest.yml
applications/GPIO/flip_trader/manifest.yml
applications/GPIO/flip_weather/manifest.yml
applications/GPIO/flip_wifi/manifest.yml
applications/GPIO/web_crawler/manifest.yml

Web Crawler v0.7
- Improved memory allocation
- App restructured
FlipLibrary v1.2
- Improved memory allocation.
- Added in Dog Facts.
- Added in Random Quotes.
- App restructured
FlipTrader v1.1
- Improved memory allocation
- Added more assets 
- App restructured
FlipWeather v1.1
- Improved memory allocation.
- Updated WiFi configuration.
- App restructured
FlipWiFi v1.1
- Fixed freeze when configs didn't exist (thanks WillyJL)
- Fixed empty Saved AP list
- Improved memory allocation
- App restructured
- WiFi Dev Board for Flipper Zero with FlipperHTTP Flash: https://github.com/jblanked/FlipperHTTP
- WiFi Access Point

Update 5 FlipperHTTP apps

---

applications/Media/image_viewer/manifest.yml

- Image viewer for flipper zero!
- N/A

image_viewer_0.1

---

applications/GPIO/gemini_ia/manifest.yml

- This application allows the Flipper Zero to communicate with Google’s Gemini AI through an ESP32 module. With this setup, users can interact with an AI directly from their Flipper Zero, asking questions and receiving responses in real time. The application provides a simple UI on the Flipper, enabling communication through text prompts and displaying AI-generated responses.
- This application requires an ESP32 module to handle the wireless communication between the Flipper Zero and the Gemini AI service. The firmware binaries needed to flash the ESP32 are included in the same repository as this app. No additional software is required.

Add manifest.yml for Gemini IA

---

applications/GPIO/flip_social/manifest.yml

- Added bearer auth
- FlipperHTTP edit by Willy-JL
- WiFi Devboard or Raspberry Pi Pico W flashed with FlipperHTTP: https://www.github.com/FlipperHTTP
- WiFi Access Point

FlipSocial Security Update (v0.6.2)

---

applications/GPIO/ublox/manifest.yml

Add GPX file support. Apologies for not naming the branch following the new convention, I didn't see the changes in the contribution document until after I had already pushed.
No changes since last release.

Update ublox to version 0.5

---

applications/GPIO/esp32_wifi_marauder/manifest.yml

Added support for latest commands in new Marauder firmware release (v1.1.0)

Update marauder app to v0.7.2

---

applications/Games/pinball0/manifest.yml

- Pinball0 v0.5
- Fixed turbo boosts
- Added basic signalling
- code cleanup
- N/A

Pinball0 v0.5

---

applications/GPIO/flip_social/manifest.yml

- Improved memory allocation
- Increased the max explore users from 50 to 100
- Increased the max feed posts from 40 to 50.
- Added loading screens.
- Added updates from Derek Jamison
- WiFi Dev Board for Flipper Zero with FlipperHTTP Flash: https://github.com/jblanked/FlipperHTTP
- WiFi Access Point

Update FlipSocial to v0.7

---

applications/NFC/metroflip/manifest.yml

- Metroflip v0.2
- Update Rav-Kav parsing to show more data such as transaction logs
- Add Navigo parser!
- Bug fixes

Metroflip v0.2

---

applications/Games/chess/manifest.yml

- Update chess to fix illegal move bug (thanks @956MB)
- N/A

Update chess to fix illegal move bug

---

applications/Games/color_guess/manifest.yml

- Reduced Code
- Removed deprecated feature (view_dispatcher_enable_queue)

Color Guess Update v1.6

---

applications/NFC/metroflip/manifest.yml

- Added 5 new cards to Metroflip v0.3

Metroflip v0.3

---

applications/GPIO/flipper_spi_terminal/manifest.yml

- It's an application for communicating with other devices over SPI.
- None

Added Flipper SPI terminal v0.1

---

applications/NFC/seader/manifest.yml

- Prevent crash when reading NTAG215
- Show error screen on picopass timeout

Bump Seader to v3.3

---

applications/Tools/fmatrix/README.md
applications/Tools/fmatrix/manifest.yml

- fmatrix is an app that displays the "matrix rain" effect (like [cmatrix](https://github.com/abishekvashok/cmatrix) for example), basically a bunch of raining characters falling down from the top of the display.
- The application does not require or utilize any external hardware, nor will any external hardware prevent the app from working properly. (TL;DR: No extra requirements needed)

Add fmatrix v0.2

---

applications/Tools/vin_decoder/manifest.yml

- [ VIN Decoder is a simple tool that allows you to decode VIN (Vehicle Identification Number) numbers. This project provides users with the ability to enter their VIN and obtain information about the vehicle, including the name of the manufacturer and the year of manufacture. It supports vehicles such as BMW, Audi, Alfa, Citroen, Lada, Ferrari, Fiat, Mercedes, etc. Vin decoder supports years from 1997 to 2024. ]
- [ none ]
- [ X] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [X ] I own the code I'm submitting or have code owner's permission to submit it
- [X ] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint …

VIN decoder

---

applications/Tools/fmatrix/README.md
applications/Tools/fmatrix/manifest.yml

v0.3:
- added menu for fmatrix 
- added a submenu for options (for configuring fmatrix)
- added options for lowercase letters, numbers, and symbols
- added options to control spawn rate, max/min speed, and max/min character trail length 
- updated README for more information about the menu and what things do
- No extra requirements

fmatrix v0.3

---

applications/Games/furious_birds/manifest.yml

Add Furious Birds game v1.0

---

applications/Tools/upython/manifest.yml

- Update to latest SDK version (fixes https://github.com/ofabel/mp-flipper/issues/6)
- Replaced speaker note constants with attribute delegation function to save space.

Update uPython to 1.7

---

applications/Tools/flipperzero_clock/manifest.yml

Update FlipperZero Clock to v1.3

---

applications/Games/quadrastic/manifest.yml

Quadrastic is a simple addicting game inspired by the [Arduboy game](https://community.arduboy.com/t/quadrastic-secure-the-point-avoid-the-enemies) of the same name.
There are no extra requirements

Add quadrastic game to the catalog

---

applications/Tools/key_copier/manifest.yml

* Support for Double Sided Key and Multiple New Key Formats by @HonestLocksmith in https://github.com/zinongli/KeyCopier/pull/20
* New formats:
| Manufacturer          | Format Name | Data Sheet                                             |
|-----------------------|-------------|-------------------------------------------------------------|
| Arrow                 | AR4         | C2                                                          |
| Master Lock           | M1          | C35                                                         |
| American              | AM7         | C80                                                         |
| Yale                  | Y2          | .025                                                        |
| Yale                  | Y11         | CX55 …

Update Key Copier 1.1

---

applications/USB/xinput_controller/manifest.yml

This app contains a full implementation of the XInput protocol, which can also be used for other uses. It lets the user use the left joystick and the A and B buttons. To test if the application works, use gamepadtester or `joy.cpl` on Windows.
A device or computer that has compatbility with Xbox controllers, **not including Xbox consoles. This is due to some security mechanisms that are not implemented.**

USB Game Controller application

---

applications/NFC/picopass/manifest.yml

- Added Save SR as legacy from saved menu
- Fix write key 'retry' when presented with new card
- Requires iClass cards to test

Bump Picopass to v1.18

---

applications/Games/drifter/manifest.yml

- Drifter is a boat game for the Flipper Zero
- N/A

Drifter v0.1

---

applications/Infrared/xbox_controller/manifest.yml

- added changelog.md and README.md in plugin repository to maintain it all in one place
- bumped version to build for latest SDK version

Update Xbox Controller plugin for latest SDK

---

applications/NFC/nfc_maker/manifest.yml

- Allow setting custom UID
- Show extra symbols for WiFi SSID/Password and Emails (by 956MB)
- Code cleanup
- None

Bump NFC Maker v1.3

---

applications/Games/pinball0/manifest.yml

- pinball0 v0.5.2
- Prevent table tilt before ball is launched
- Widened bottom portal on table Endless to prevent ball loss
- Updated SDK to 1.2
- N/A

pinball0 v0.5.2 - bug fixes

---

applications/NFC/metroflip/manifest.yml

Bump Metroflip to v0.5

---

applications/GPIO/gpio_explorer_app/manifest.yml

application initialization

---

applications/Infrared/xremote/manifest.yml

- Bugfix, on first open the folder to save files didn't exist 
- Bugfix, Loop Transmit now also works when using SubGHz RAW recordings

Cross Remote Version 3.1

---

applications/GPIO/401_light_msg/manifest.yml

- LightMessenger companion app
- Need lab401's Light messenger hardware addon

Update meta data, application.fam and manifest.yaml

---

applications/Tools/pet_your_dolphin/manifest.yml

It's an app that let's you "pet" your dolphin to improve its mood and receive some XP. It features animations that differ depending on the dolphin's current mood and a simple, intuitive interface.
No extra requirements.

Added manifest for Pet Your Dolphin app

---

applications/USB/portal_of_flipper/manifest.yml

- USB Emulator for NFC Reader that is used with a wii/wii u/playstation game
- Game console (non-xbox)
- Game (Skylanders: Giants, Skylanders: Trap Team, Skylanders: Superchargers)

Portal of Flipper v1.0

---

applications/GPIO/401_light_msg/manifest.yml

- Rework on config file's logic
- Merged from jamisonderek's PRs
- Mirror mode
- Fix accelerometer
- Word by word mode
- Sensitivity increase
- Letter width setting
- R3dBlu3 animation
- Require Lab401's Light Messenger addon

Tixlegeek/401 light msg 1.2

---

applications/Tools/fordradiocode/changelog.md
applications/Tools/fordradiocode/manifest.yml

Simple app to generate a 4 digit code from a 7 digit serial. Enter the serial number either beginning with 'M' or 'V' plus the 6 digit number and the app will automatically display the required 4 digit code, displayed in real-time.
Requires "radiocodes.bin" to be manually copied to SD Card as it is too large to bundle with the app.
Available from my GitHub Repo.

FordRadioCodes - Initial Release v0.1

---

applications/Infrared/xremote/manifest.yml

- Added support for Infrared GPIO boards

Cross Remote 3.2, new GPIO IR Support

---

applications/Games/deadzone/manifest.yml

This is the first release of the video game DeadZone. It's a 2D video game where you can fight AI-powered NPCs and avoid falling obstacles. There is a high-score system implemented, allowing you to remember your best moments in the game.
None required.

Submission of DEADZONE

---

applications/Infrared/lidar_emulator/manifest.yml

LIDAR Emulator (v0.1)

---

applications/GPIO/flipper_gb_printer/manifest.yml

- Implemented GB printer protocol compression support to correctly receive images from a wider range of games.
- Game Boy/Color/Advance, Game that can print, interface EXT cable to flipper

GPIO: flipper_gb_printer: bump to v0.5

---

applications/Tools/key_copier/manifest.yml

Update Key Copier 1.2

---

applications/Tools/totp/manifest.yml

- Updated Authenticator to [v5.17.0](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v5.17.0)
- N/A

Updated Authenticator to v5.17.0

---

applications/Games/fighterjet/manifest.yml

Game about flying fighter jet and hunting down enemies

Adds fighterjet game

---

applications/GPIO/ina_meter/manifest.yml

This is an application designed to read current and power monitors from Texas Instruments, including INA219, INA226, and INA228. It provides real-time voltage and current measurements by interfacing with these sensors over I2C.
The application requires at least one supported INAxxx sensor to be connected to GND, SCL (C0), and SDA (C1) pins.

Add INA Meter v0.1

---

applications/GPIO/servotesterapp/README.md
applications/GPIO/servotesterapp/manifest.yml

The RC Servo testing application, with different logic, avoids most of the [servo tester application's existing issues](https://github.com/spin7ion/flipper-servotester/issues).
The RC servo under test. Directly connected to power and A7 GPIO pin.

Adding servotesterapp to the catalog

---

applications/GPIO/401_light_msg/manifest.yml

- Bitmap editor enhancement
- Fixes and enhancement in display model
- Added authentic bitmaps 2000's operator logos as assets
- Changed apps_data to apps_assetsfor storing datas and bitmaps
- Requires a lightmessenger hardware module

Bump to v1.3

---

applications/USB/portal_of_flipper/manifest.yml

- Fix some issues with portal emulation
- Emulate the portals audio via the speaker on the flipper
-  Game console (non-xbox one)
-  Game (Skylanders: Giants, Skylanders: Trap Team, Skylanders: Superchargers)

Bump USB/portal_of_flipper to 1.2

---

applications/GPIO/servotester/README.md
applications/GPIO/servotester/manifest.yml

Fixing lagging UI in the Servo Tester application already existing in the catalog
Switching to a better-updated source code repository. 
Works alone without external hardware, but an externally connected servo is needed to make the effect of the application visible.

Update of original Servo Tester application  

---

applications/Media/tuning_fork/manifest.yml

- Redesign tunings hierarchy
- New tunings
- UI Improvements
- Stability fixes
- None

Tuning Fork to 2.1

---

applications/Games/spaceimpactii985e/manifest.yml

Flipper zero port of the copy (https://github.com/VoidXH/Space-Impact-II) of the classic mobile game Space Impact II

Adds Space Impact II manifest

---

applications/GPIO/ina_meter/manifest.yml

- Added current/voltage recording to the CSV file
- Moved `ledBlinking` from `[Sensor]` to `[App]` section in configuration file
- Fixed menu item linking to wiring screen

Bump INA Meter to v0.2

---

applications/Bluetooth/pc_monitor/manifest.yml

- Fixed app for latest firmware
- Desktop app QR code
- Minor code refactoring
[Desktop app](https://github.com/TheSainEyereg/flipper-pc-monitor-backend) that is currently being reworked.

PC Monitor 1.1.0

---

applications/GPIO/flipper_spi_terminal/manifest.yml

- Flipper SPI Termin v0.3
- For a full change log see https://github.com/janwiesemann/flipper-spi-terminal/compare/v0.1...v0.2
- Noting has changed compared to v2.0. Fix for #617 
- A nice pancake or a fish for your flipper

Flipper spi terminal v0.3

---

applications/Bluetooth/pc_monitor/manifest.yml

- Mistook Willy-JL in credits with i2c-tools developer
- Back-end app for PC

PC Monitor README update

---

applications/NFC/nfc_maker/manifest.yml

- Added support for creating more types of tags:
- MIFARE Classic Mini 0.3K
- MIFARE Classic 1K
- MIFARE Classic 4K
- SLIX
- SLIX-S
- SLIX-L
- SLIX2
- Added memory size information to Tag Type list
- Save errors don't return to the main menu anymore
- Added version number to title screen
- None

Bump NFC Maker v2.0

---

applications/Tools/totp/manifest.yml

Updated Authenticator to [v5.17.1](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v5.17.1)
N/A

Updated Authenticator to v5.17.1

---

applications/Bluetooth/pc_monitor/manifest.yml

- Blue LED blinks on data reception
- Backlight is now enabled during communication
- PC app

PC Monitor 1.1.2

---

applications/GPIO/ina_meter/manifest.yml

- Fixed recording being disabled when LED blinking was off
- Disabled led blinking during battery charging

Bump INA Meter to v0.3

---

applications/Tools/key_copier/manifest.yml

v1.3
* A new UI/workflow for key format selection by @Offreds's PR
* Added QR code directing user to @TalkingSasquach's awesome video from decoding keys to 3D-printing copies.
- None

Key copier 1.3

---

applications/NFC/passy/manifest.yml

- Passport reader (eMRTD), shows MRZ data from DG1 so far
- Have passport
- Only tested with US and Chilean passports so far

Passy: passport reader

---

applications/GPIO/ina_meter/manifest.yml

v0.4:
- Added support for an alternate shunt resistor, switchable via long press of the down button on the gauge screen.
- Fixed shunt resistor dialog - it  now closes by pressing the save button
- Fixed confirmation dialog shown when exiting app

Bump INA Meter to v0.4

---

applications/NFC/passy/manifest.yml

- Adds reading and saving the photo from DG2
- Adds reading and saving the signature from DG7 (if present)
- Adds reading other optional DG
(Sorry for opening this right after the other was merged, but I'd been working on this and hadn't wanted to disrupt QA'ing the previous version)
- Requires a passport with eMTRD support

Bump passy to 1.0

---

applications/Misc/executor_keychain/manifest.yml

- **Flipper Keyller** is an app for the Flipper Zero that emulates the iconic sounds of the classic 80s keychain
- Nop

Flipper Keyller

---

applications/Bluetooth/pc_monitor/manifest.yml

- Fix for BLE API changes
- Back-end app running on user's PC

PC Monitor 1.1.3

---

applications/NFC/seos/manifest.yml

- Seos compatible reader/emulator (NFC/BLE)
- Requires unreleased flipper firmware with mbedtls AES (https://github.com/flipperdevices/flipperzero-firmware/pull/4092) and improved BLE advertising (https://github.com/flipperdevices/flipperzero-firmware/pull/4151)
- Requires either a Seos card that uses keys of all zeros (Unlikely to find) or a proxmark3 (`hf seos pacs` uses zero keys by default)

Seos compatible reader/emulator (NFC/BLE)

---

applications/GPIO/air_mouse/manifest.yml

- Updating existing application
- See README for hardware requirements

Update FlippAirMouse to build with SDK 85

---

applications/GPIO/ina_meter/manifest.yml

- Fixed build with the latest SDK version 1.3.0-rc

Update INA Meter to v0.5

---

applications/Infrared/midea_ac_remote/manifest.yml

- Remote control app for Midea AC units compatible with "RG10B(B)/BGEF" remote type and similar.
N/A

Add Midea AC Remote v1.0

---

applications/Tools/flipper95/manifest.yml

- Updated Flipper95 for firmware 1.3.2, and fixed a memory leak when using its CLI commands.
Fixes https://github.com/CookiePLMonster/flipper-bakery/issues/6 (I wonder if it'll auto-close).

Updated Flipper95 to v1.1

---

applications/Infrared/tamagometer_companion/manifest.yml

- Updated to work with firmware 1.3.2 rc f7, no functional changes

Update tamagometer_companion to v0.3

---

applications/NFC/passy/manifest.yml

- According to @luu176 now it supports French passports!
- A french passport to test against?

Bump passy to 1.1

---

applications/GPIO/flipper_spi_terminal/manifest.yml

- Fixes for Flippe firmware v1.3.x
-  A potato

Flipper SPI Terminal v0.4

---

applications/GPIO/fn_test/manifest.yml

-  Update to flipper SDK version 1.3.2

fn_test SDK 1.3.2 support

---

applications/Tools/blinker/README.md
applications/Tools/blinker/manifest.yml

- A Flipper Zero application that blinks LEDs with a decreasing frequency over time. Unlike traditional Pomodoro timers, it provides visual feedback through LED blinks that gradually slow down.

Cupprum/blinker v1.0

---

applications/GPIO/signal_generator/manifest.yml

- signal_generator: fixed crash on start, added changelog file
- run app, validate there's no crashes

signal_generator: fixed crash on start, added changelog file

---

applications/GPIO/uv_meter_as7331/manifest.yml

Measure UV radiation using the AS7331 sensor.
The AS7331 sensor:
* https://ams-osram.com/products/sensor-solutions/ambient-light-color-spectral-proximity-sensors/ams-as7331-spectral-uv-sensor
* https://www.sparkfun.com/sparkfun-spectral-uv-sensor-as7331-qwiic.html

Add UV Meter v1.0

---

applications/Tools/upython/manifest.yml

- Update to latest SDK version (fixes https://github.com/ofabel/mp-flipper/issues/9)

Update uPython to 1.8.0

---

applications/NFC/passy/manifest.yml

- Show both issuing state and nationality (Thanks @portasynthinca3)
- Handle Passport numbers < 9 char
- Fix bug with SELECT AID APDU Le
- New Icon (Thank you @equipter for the idea)
- a eMTRD (passport/id card) that supports BAC

Bump passy to 1.3

---

applications/GPIO/fcom/manifest.yml

- Update flipper firmware APIs to fix compatibility
- No change

Update fcom to 1.5

---

applications/Infrared/flame_rng/manifest.yml

This app uses the flipper zero's IR transceiver as an entropy source for a Random Number Generator. It's really simple, just flick a lighter a reasonable distance away from the flipper, or point a remote at the IR transceiver to generate a number. It outputs the number on to the screen, and by pressing the center button you can also save the last 5 numbers to the SD Card.
None Here! I am using a stock flipper zero!

Orion w06/flame rng/0.01

---

applications/NFC/weebo/manifest.yml

- A Flipper Zero NTAG215 parser, writer, emulator, remixer, duplicator.
- `key_retail.bin` (reviewer: feel free to reach out to me if you can't find it)
- A Flipper NFC dump of an Amiibo with all pages unlocked and correct PWD
- For writing: a factory default NTAG215

New app: Weebo

---

applications/Tools/totp/manifest.yml

- Updated Authenticator to [v5.18.0](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v5.18.0)
- N/A

Updated Authenticator to v5.18.0

---

applications/NFC/udecard/manifest.yml

An application for the analysis of student/employee ID cards from the University of Duisburg-Essen (Intercard).
This application is able to read the card's data and display it in a human-readable format.
It is also possible to load a previously saved card.

Add UDECard v1.0.1

---

tools/bundle.py
tools/flipp_catalog/__init__.py
tools/flipp_catalog/manifest.py

- tools: fixed exception handling

tools: fixed exception handling

---

applications/Infrared/flame_rng/manifest.yml

Improved the RNG with the hardware RNG and some bit mixing, also added a new app icon that doesn't look like dookie.
None here!

Update Flame_RNG to v0.3

---

applications/GPIO/swd_probe/manifest.yml

- Update app to latest api
- none

Update SWD Probe

---

applications/Games/drifter/manifest.yml

- Add new game mode (map moves instead of ship)
- Add one more high score digit
- Update checkout action to v4 in build.yml
- N/A

Update drifter v0.2

---

applications/GPIO/401_light_msg/manifest.yml

- lab401's lightmessenger companion app v1.4.1
- Need lab401's lightmessenger hardware module

bump to v1.4.1

---

applications/Tools/totp/manifest.yml

Updated Authenticator to [v5.19.0](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v5.19.0)
N/A

Updated Authenticator to v5.19.0

---

applications/NFC/udecard/manifest.yml

Flipper application to analyse student ID cards from the University of Duisburg-Essen (Intercard).

Update UDECard to v1.0.2

---

applications/Tools/fmatrix/README.md
applications/Tools/fmatrix/manifest.yml

- fmatrix (version 0.3.5) is a simple FZ app that displays the "matrix rain" effect on the Flipper Zero's screen.
- This is a small update that adds an inverted mode, which makes everything white appear black and vice versa when enabled.
None

fmatrix v0.3.5

---

applications/iButton/ibutton_converter/manifest.yml

- Feature: New Cyfral convert options: C2 Alt (by @li0ard)
- Fixed: Incorrect Cyfral C4 data generation
- Minor UI rework
- None

ibutton_converter v1.1

---

applications/USB/portal_of_flipper/manifest.yml

- Implement authentication for the xbox 360. This means you no longer need a modded console.
-  Game console (non-xbox one)
-  Game (Skylanders: Giants, Skylanders: Trap Team, Skylanders: Superchargers)

Bump USB/portal_of_flipper to 1.3

---

applications/Tools/password_manager/manifest.yml

- Feature: if the username is not set, it will only write **password + \n**
- Feature: added minimal parser per special character in the credentials file: "\"  -> "\\\\" and ","  -> "\\,"

updated password_manager to 1.2

---

applications/NFC/seos/manifest.yml

- Add support for reading Seader files that have SIO
- Add custom zero key ADF OID (`0.3.1.7.9.0.0.0.0.0`/`030107090000000000`)
- Add persisting and reading of diversified keys, ADF response and ADF OID
- Requires either a Seos card that uses keys of all zeros (Unlikely to find) or a proxmark3 (`hf seos pacs` uses zero keys by default)

Bump Seos compatible to v1.1

---

applications/GPIO/sio2flip/manifest.yml

- Added disk swapping feature accessible via the FDD menu
- Improved support for hard disk images
- Increased maximum US Doubler speed to 73.7 KBd
- Fixed XF-551 high-speed mode
None

Update sio2flip to v0.4

---

applications/GPIO/camera_suite/manifest.yml

Changelog:
- Updating the row and column iteration boundaries in the serial stream to cover the full 128×128 image.
- Changing the camera configuration from QQVGA to 128×128 mode.
- Adjusting buffer size macros and pixel offset calculations in the camera suite view to accommodate the new image dimensions.
- New contributor @rnadyrshin, thank you!

Update "Camera Suite" application to v1.9

---

applications/Tools/qrcode_generator/README.md
applications/Tools/qrcode_generator/manifest.yml

A simple application to generate new and display saved QRCodes on the flipper zero.

Add application 'QRCode Generator'

---

applications/Tools/flip_crypt/manifest.yml

- FlipCrypt is an app to encrypt, decrypt, and hash text using a variety of classic and modern cryptography tools.
- No additional hardware or software is required to run.

Added app 'Flip Crypt'

---

applications/GPIO/esp32_wifi_marauder/manifest.yml

Added support for latest commands in new Marauder firmware release (v1.6.0)

Update marauder to v0.7.3

---

applications/NFC/udecard/manifest.yml

Analyse student ID cards from the University of Duisburg-Essen (Intercard).
This application allows reading directly from the card or loading a previously saved dump.
Changes since last submission: Important fix regarding the usability on standard firmware.

Update UDECard to 1.0.3

---

applications/Games/wave/manifest.yml

Update Wave to v0.2

---

applications/NFC/passy/manifest.yml

- uppercase all letters in passport number
- Confirm support for more countries
- eMTRZ (passport) with BAC support

Bump Passy to 1.4

---

applications/Infrared/xbox_controller/manifest.yml

Update version, added long press

update Xbox IR Controller app

---

applications/NFC/seos/manifest.yml

- No functional code changes, just moving to GitHub (slowly moving all projects there)
- Requires zero key seos card / zero key emulation OR knowing the standard keys (not public).

Bump Seos to v1.2 (move to GitHub)

---

applications/Bluetooth/anki_remote/manifest.yml

- Fixed bug where "Space" appeared as a blank " " in settings menu
- Added reset keys option; removed default key mappings
- Updated screenshots and README to reflect the changes above
- Laptop, smartphone, tablet, PC, or any device that can connect to Bluetooth and use an HID keyboard

Update Anki Remote to v1.1

---

applications/Tools/flip_crypt/manifest.yml

Added more tools, changed menu structure, added NFC, QR code gen, and saving output to text file.
None.

Update FlipCrypt to v0.2

---

applications/Tools/key_copier/manifest.yml

- v1.4
Added Weiser WR3 key format support by @lightos
- None

Key copier 1.4

---

applications/GPIO/co2_logger/manifest.yml

- App that connects to MH-Z19 CO2 sensors via Flipper Zero GPIO pins, displays the CO2 PPM reading, and logs it to a co2_log.csv file in the apps_data/co2_logger folder. 
- MH-Z19 CO2 sensor
- [y ] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [ y] I own the code I'm submitting or have code owner's permission to submit it
- [ y] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

new gpio app: co2_logger

---

applications/Media/usb_midi/README.md
applications/Media/usb_midi/manifest.yml

- Turn flipper it into a monophonic USB-MIDI instrument.
- Source of MIDI commands: computer, MIDI-keyboard, _etc._

Add USB-MIDI

---

applications/GPIO/ina_meter/manifest.yml

Updates ina_meter to v0.6. This is a bugfix release:
- Fixed deadlock when closing the datalog file
None

Update ina_meter to v0.6

---

applications/Tools/flip_crypt/manifest.yml

- Added ROT-13 cipher
- Added MD2 hash
- Back-end improvements regarding storage
N/A

Update FlipCrypt to v0.3

---

applications/GPIO/sio2flip/manifest.yml

Updates sio2flip to v0.5:
- Added new high-speed options (up to 127K)
- Improve XEX file loading compatibility (RUNAD is executed only after entire load process)
None

Update sio2flip to v0.5

---

applications/Tools/flip_crypt/manifest.yml

- Fixed NFC emulation issue
- N/A

Update FlipCrypt to v0.4

---

applications/Games/flipper_hero/manifest.yml

- Record table! yay
- Updated for SDK version compatibility
- Fixed FlipperFormat header include for newer SDK compatibility
-  gui

 Update flipper hero game to v1.3.0, add record table

---

applications/Infrared/xbox_controller/manifest.yml

- Added Media Control view
Nope

Update Xbox controller to v1.5

---

applications/GPIO/gpio_sentry_safe/manifest.yml

- New interface
- Customised settings (you can chose your code and type of code)
- Help page added

Update gpio_sentry_safe v2.0

---

applications/Tools/key_copier/manifest.yml

- Added Suzuki SUZ18 key type by @RIcePatrol 
- None

Update Key Copier v1.5

---

applications/Tools/flip_crypt/manifest.yml

- Fixed some typos, updated Github username.
- N/A

Update FlipCrypt to 0.5

---

applications/GPIO/esp32_wifi_marauder/manifest.yml

Update marauder app to v0.7.5

---

applications/Sub-GHz/flipper_share/manifest.yml

- flipper_share v1.0. Flipper Share is a file sharing app for Flipper Zero.
- You need two flippers to try the app

flipper_share release v1.0

---

applications/GPIO/esp_flasher/manifest.yml

Update esp flasher to v1.7

---

applications/NFC/nfc_maker/manifest.yml

- Added support for Empty record type to make blank NDEF tags
- None

Bump NFC Maker v2.1

---

applications/Tools/flip_crypt/manifest.yml

- RAM optimizations and Porta Cipher addition
- N/A

Update FlipCrypt to v0.6

---

applications/Sub-GHz/flipper_share/manifest.yml

- GUI Improvements
- Added more detailed screenshots
- Docs updated
- Bump version to v1.1
- You need two flippers to check the app

flipper_share: v1.1: improved GUI, docs

---

applications/NFC/seader/manifest.yml

- Improve DesFire support
- Add SIO Parsing
- Requires addon: UART to mini-SIM adapter and HID SAM.

Bump Seader to v3.4

---

applications/NFC/picopass/manifest.yml

- move to GitHub
- parse SIO
- Auto NR-MAC
- access to iClass card

Bump Picopass to v1.20

---

applications/USB/mouse_jiggler/README.md
applications/USB/mouse_jiggler/manifest.yml

This simple application is a fork of Matthew Willard's [flipper-mouse-jiggler](https://github.com/matthewwwillard/flipper-mouse-jiggler). Unlike other mouse jiggler implementations for the Flipper Zero, this one introduces an element of randomness to the movement patterns instead of performing a simple back-and-forth cycle.
Since the purpose of this application is to emulate a USB mouse, the Flipper must be plugged in to a computer in order for it to be useful. Additionally, while the application is running, it will not be possible to use qFlipper to control the Flipper.

Publish Mouse Jiggler v1.0 to Flipper Labs
