applications/GPIO/pokemon/manifest.yml
Add Pokemon Trading manifest to Flipper Catalog
Pokemon exchange from Flipper Zero to Game Boy for Generation I (Pokemon Red, Blue, Yellow) using GPIO
- No
=> Add Pokemon Trading manifest to Flipper Catalog

applications/NFC/seader/manifest.yml
~~I know the app catalog hasn't been launched, I just wanted to try out the process.  No rush.~~ I see there are merged PRs already, I guess I'm not early.
I did notice the markdown support (https://github.com/bettse/flipper-application-catalog/blob/main/documentation/Manifest.md#markdown-support) didn't work with my readme since I'd craft it originally for GitLab/GitHub.  The manifest validation tool was really helpful.
- Allows reading HID iClass SE and HID Seos cards when used with HID SAM.
- Requires hardware add on to interface with SAM over UART.  
- Can be https://github.com/killergeek/nard or https://www.mikroe.com/smart-card-2-click 
- plus the HID SAM
=> Seader manifest

applications/GPIO/esp_flasher/manifest.yml
ESP flasher now automatically enters the bootloader and resets supported boards (including flipper official wifi dev board) using RTS and DTR pins. Also added notifications (blue LED when flashing, vibrate when done).
=> Update ESP flasher (v1.1)

applications/RFID/key_generator/README.md, applications/RFID/key_generator/manifest.yml
- This PR fixes the issue described in #80 - the app didn't have `fap_version` in its manifest, which led to it being replaced by an automatically geenerated version.
- none
=> Add "EM4100 key generator" app - now with the proper version

applications/GPIO/max31855/manifest.yml
- Add MAX31855 Thermocouple Sensor App
- Requires MAX31855 Sensor connected to GPIO
=> Add MAX31855 Thermocouple Sensor App

applications/GPIO/esp32_wifi_marauder/manifest.yml
Update wifi marauder app to v0.6.3 to support new bt wardrive and sourapple commands
=> Update wifi marauder app to v0.6.3

applications/Tools/wch_swio_flasher/README.md, applications/Tools/wch_swio_flasher/manifest.yml
WCH SWIO debugger and flasher emulated on Flipper Zero tool - tool for flashing and debugging CH32V003 chip.
CH32V003 chip connected to Flipper Zero with external pull-up resistor required. Wiring described inside application itself.
You can found more info on project Readme.
=> Add WCH SWIO Flasher v1.0

applications/Tools/knit_counter/manifest.yml
- This is a counter which saves the count after exiting. 
- This can be used as a knitting row counter.
- None
=> Add knitting row counter app

documentation/Contributing.md, tools/bundle.py
Not an application submission.
Proposing adding some instructions to install the latest stable SDK as part of the contribution guide. 
Without running `ufbt update` or otherwise populating the ufbt's SDK dir, these instructions lead to a somewhat opaque error when running `tools/bundle.py`:
```
$> python3 tools/bundle.py --nolint applications/Infrared/ir_intervalometer/manifest.yml bundle.zip
10:24:51.235 [E] Could not find ufbt state dir: Command '['ufbt', 'status', 'sdk_dir']' returned non-zero exit status 1.
```
Running `ufbt status sdk_dir` will return the SDK path without obvious error, but exit with a non-zero code. 
```
$> ufbt status sdk_dir
/home/luna/.ufbt/current
$> echo $?
1
```
This PR add instructions to install the latest stable sdk via `ufbt` into the virtual environment …
=> Add ufbt SDK Installation Instruction for Contibuting Guide

applications/NFC/seader/manifest.yml
- Fix saving diversifier for iClass SE (broke during NFC refactor)
- Add support for Desfire EV2
- Add capturing SIO for Desfire EV1/EV2
- Rename "Load" menu to "Saved" to align with NFC and RFID apps
- UI flow improvements
=> Seader: Bump to v2.2

applications/GPIO/camera_suite/manifest.yml
- Update "[ESP32] Camera Suite" application fap from v1.4 to v1.5.
- Removes use of an image that no longer exists in the new firmware.
=> Update "Camera Suite" application to v1.5

applications/NFC/seader/manifest.yml
- Bug fix for the CSN when saving as picopass.  We used to use a hard coded CSN because it didn't matter and we didn't capture the real CSN, but now we want to use the CSN we captured.
=> Seader: Bump to v2.3

applications/GPIO/ublox/manifest.yml
- Update ublox to compile under firmware 0.99-rc (fixes https://github.com/liamhays/ublox/issues/1) by changing FuriHalRtcDateTime to DateTime.
Generating the bundle gave errors about `SCons.Node` not having an attribute `FS`, but I think that happened last time I updated this app.
=> Update ublox commit to v0.4.

applications/GPIO/air_mouse/manifest.yml
- Updating existing app
On a related note, is there a way to tell the bot to [ignore old SDKs](https://catalog.flipperzero.one/application/6499e5efc3d2eeadb4bd400b/page)? Some way of specifying minimum required API level maybe?
=> Update BMI Air Mouse

applications/GPIO/noptel_lrf_sampler/manifest.yml
New in version 1.1:
- Added LRF information display
- Save and restore the configuration
-  Nicer about screens
=> Updated noptel_lrf_sampler to 1.1

applications/NFC/seader/manifest.yml
- Adds format parsing for H10301 and C1k35s
- After reading card, if it is H10301 or C1k35s then a "parse" menu will show above "save"
=> Seader: v2.7

applications/GPIO/noptel_lrf_sampler/manifest.yml
New in version 1.5:
- Added LRX laser tester
- Added IR pointer tester
*[Note: unlike the rest of this app which requires a Noptel rangefinder, you actually can test if those two new functions work properly with a TV remote if you want: they're just simple IR detectors, just driving the rangefinder to generate a signal the Flipper can detect at the same time, but they don't strictly need the rangefinder to be present]*
=> Updated noptel_lrf_sampler to 1.5

applications/GPIO/noptel_lrf_sampler/manifest.yml
New in version 1.6:
- Added baudrate setting
- Faster automatic SMM sampling rate
- Display the supply voltage and receiver temperature in the LRF info view
- Keep the backlight on when testing the LRX laser or the IR pointer
- Undocumented feature can be enabled with a special configuration file (manufacturer only)
=> Updated noptel_lrf_sampler to 1.6

applications/GPIO/magspoof/manifest.yml
- My MagSpoof app is a port of Samy Kamkar's original MagSpoof project, enabling wireless transmission of magstripe data.
- At present, emulation is supported with the assistance of a GPIO module consisting of an H-bridge, a coil, and a capacitor.
- The most recent revisions include the ability to set/save the pins used.
- Additional code is present that tests internal TX, and external (UART) RX; as these features are WIP and/or skunkworks, they currently are only accessible when the debug flag is set.
- There is code in my application that is FW-specific making use of additional GUI elements only available in CFWs; despite this, the code compiles (and works) happily across all current FWs, with `#ifdef FIRMWARE_ORIGIN_Official` used to conditionally replace / remove elements that differ …
=> Add MagSpoof v0.7

applications/GPIO/noptel_lrf_sampler/manifest.yml
New in version 1.7:
- Added USB serial passthrough function
*[Note: this USB serial passthrough function is generic. You can test it with any UART device if you want to ensure that it works. It doesn't have to talk to a Noptel rangefinder. The functionality is exactly the same as the USB-UART bridge in the GPIO app, but this re-implementation handles high-speed serial traffic properly, and it's part of this app because the PC1 pin needs to be high to control the rangefinder's power supply.]*
=> Updated noptel_lrf_sampler to 1.7

applications/GPIO/noptel_lrf_sampler/manifest.yml
New in version 1.8:
- Added serial traffic monitor in the USB serial passthrough view
- Added USB serial passthrough channel setting
- Added utility to decode LRF serial traffic logged in the Flipper Zero CLI in real time
=> Updated noptel_lrf_sampler to 1.8

applications/GPIO/flipagotchi/manifest.yml
- The flipagotchi application allows a pwnagotchi device (with the PwnZero plugin installed) to communicate with the Flipper Zero over serial
- It displays the screen of the pwnagotchi on the Flipper 
- Requires a connection to a pwnagotchi over UART and for that pwnagotchi to have the PwnZero plugin installed
- All steps specified in detail in the repository (https://github.com/Matt-London/pwnagotchi-flipper.git)
=> Add Flipagotchi v2.0.0

applications/GPIO/noptel_lrf_sampler/manifest.yml
New in version 1.9:
- Correctly display the bytes at the left-hand side of the serial traffic screen in the passthrough view
- Free the UART receive stream buffer in the main thread rather than in the receive thread
- Added code to turn on the +5V pin as well as the PC1 pin when the app is running - currently compiled out
- Minor corrections
=> Updated noptel_lrf_sampler to 1.9

applications/GPIO/flipboard_blinky/manifest.yml
- This application turns the FlipBoard MacroPad into a blinky badge!  See https://youtu.be/z0cV6lG5wxc?t=151 for TalkingSasquach demo of the older version of the FlipBlinky application.
- I recommend the FlipBoard, but if you want to make something similar... use 4 WS2812B LEDs connected in a chain, with the data-in of the first LED going to PC3.  The switches are on PA6, PA4, PB3, PB2.  The status LED is on PA7.
=> flipboard_blinky v3.5

applications/GPIO/flipboard_keyboard/manifest.yml
- This application turns the FlipBoard MacroPad into a USB/BLE keyboard!  Each button (or button combination) on the MacroPad will send keystrokes via the USB or BLE (if USB cable is not connected) keyboard.  It will also play different tones, so you can use it as a musical keyboard as well.
See https://youtu.be/z0cV6lG5wxc?t=345 for TalkingSasquach demo of the older version of the FlipKeyboard application.
See https://www.youtube.com/shorts/LmEUcI4w4QQ for demo of playing a song with older version of the application.
- This application requires the FlipBoard hardware accessory from MakeItHackin; which is available on tindie and Etsy.  The FlipBoard is a 4 button MacroPad with a colorful LED connected to each button.  Ordering directions can be found in the readme or by scanning the QR …
=> Flipboard_Keyboard v3.6

applications/GPIO/flipboard_signal/manifest.yml
- This application turns the FlipBoard MacroPad into a Sub-GHz/IR remote!  Each button (or button combination) on the MacroPad will send a Sub-GHz signal (if configured) and then a set of Infrared codes (if configured).
See https://youtu.be/z0cV6lG5wxc?st=425 for TalkingSasquach demo of the older version of the FlipSignal application.
See https://youtu.be/uDaISCAcKpk for demo of both Sub-GHz and IR sequences.
- I recommend the FlipBoard, but if you want to make something similar... use 4 WS2812B …
=> FlipBoard Signal v3.10

applications/GPIO/flipboard_keyboard/manifest.yml
This is an updated application for the FlipBoard Keyboard application.  The difference between version 3.7 and 3.6 is that it has a bug fix where a memory address that wasn't allocated was getting freed, which sometimes caused a crash on application exit.
- I recommend the FlipBoard, but if you want to make something similar... use 4 WS2812B LEDs connected in a chain, with the data-in of the first LED going to PC3.  The switches are on PA6, PA4, PB3, PB2 (and connect to GND momentarily when …
=> FlipBoard Keyboard v3.7

applications/Sub-GHz/hc11_modem/manifest.yml
- HC-11 wireless modem emulator for the Flipper Zero.
The app relays USB serial data to/from a HC-11 module wirelessly on 444.4 → 439.0 MHz, or to/from another Flipper running the app.
This is the first release.
- A [HC-11 wireless RF UART communication module](https://www.hc01.com/goods/640e91920be12d0114404c98) from [HC-Tech](https://www.hc01.com/). This module is not sold directly by HC-Tech but available from distributors around the world. Documentation of the module in English [here](https://www.elecrow.com/download/HC-11.pdf).
=> Added HC-11 wireless modem emulator app manifest

applications/NFC/nfcurl/manifest.yml
[NFC URL](https://github.com/y-dejong/nfcurl) is a simple application to generate NFC Tags from a URL.
Features:
- Generate http(s), (s)ftp, mailto, etc. URLs
- Save a list of URLs for later use
- Export to a Flipper NFC Tag file (.nfc)
=> New app: NFC URL

applications/GPIO/fcom/README.md, applications/GPIO/fcom/manifest.yml
Digimon F-Com is an application used to connect to Digimon Virtual Pet devices. Digimon virtual pets have a 2 or 3 prong bus that they use to communicate for the purposes of transferring a pet from one device to another, battling, or evolving. Digimon F-Com can act as passthrough serial device so that an Android, iPhone, or computer applications can drive the interactions or it can drive them itself from files the user places on the device.
A voltage divider circuit (as described in the application repository) is required to convert the flipper's 3.3v signal to the (roughly) 2.7v the virtual pets use
=> Digimon F-Com v1.4 (Initial application)

applications/GPIO/flipboard_keyboard/manifest.yml
- This version has a bug fix for hanging issue on newer frameworks.  Freeing the popup resources was causing a hang later on, the fix is to free the popup at application exit.
- This version still requires a FlipBoard or similar GPIO hardware.  Reproducing the hang on new firmware prior to the fix (does not require hardware) was: Launch app, wait for popup to be dismissed, About page, press down button 4 times, application would hang.
=> Flipboard Keyboard 3.9

applications/GPIO/flipboard_signal/manifest.yml
- This version has a bug fix for hanging issue on newer frameworks. Freeing the popup resources was causing a hang later on, the fix is to free the popup at application exit.
- This version still requires a FlipBoard or similar GPIO hardware. Reproducing the hang on new firmware prior to the fix (does not require hardware) was: Launch app, wait for popup to be dismissed, About page, press down button 4 times, application would hang.
=> Flipboard Signal 3.11

applications/Sub-GHz/fmf_to_sub/manifest.yml
- This application converts Flipper music files into Sub-GHz files, which can then be heard by radios or Flipper Zero devices.
- Input files: Flipper Music Format (.FMF) or compatible comma delimited text (.TXT)
- Output file: Flip##.sub (Sub-GHz RAW file format).
- No hardware is required.  The files written are optimized for the "Flipboard Signal" application, but you can use the "Sub-GHz" application to send the files too.
=> fmf_to_sub v1.0

applications/RFID/t5577_writer/manifest.yml
- This app allows user to write raw data onto T5577 fobs. 
- This app allows user to configure that T5577's modulation, RF clock, and user block number. 
- This app allows user to edit raw block data on Flipper Zero using the byte input interface.
- This app can save and load raw T5577 files in .t5577 Flipper format. Example [here](https://github.com/zinongli/T5577_Raw_Writer/blob/main/examples/Tag_1.t5577).
- [Repo](https://github.com/zinongli/T5577_Raw_Writer)
- Nothing needed. Every function can be achieved with a Flipper Zero.
=> New App: T5577 Raw Writer v1.2

applications/GPIO/pokemon/manifest.yml
- Add ability to reset trade state without affecting currently configured Pokemon
Ownership of the repo was transferred to me which is why the github URL has changed.
- GPIO connection to Game Boy via link cable
- Gen I or II Pokemon game
=> GPIO: pokemon: bump to 2.1

applications/GPIO/flipper_gb_printer/manifest.yml
- Adds support for capturing zero margin prints as a single image (this is the same process a real printer uses to print out an infinitely tall image).
- Handling of images of different heights (up to the max 144px).
- Adds pinout selection to support more interfaces.
- Game Boy, Link Cable interface to Flipper, Game Boy game that has Game Boy Printer support.
=> GPIO: flipper_gb_printer: bump to v0.2

applications/GPIO/noptel_lrf_sampler/manifest.yml
New in version 2.0:
- Removed call to view_dispatcher_enable_queue() which has been deprecated
=> Updated noptel_lrf_sampler to 2.0

applications/Sub-GHz/hc11_modem/manifest.yml
- HC-11 wireless modem emulator for the Flipper Zero
New in version 1.1:
- Removed call to view_dispatcher_enable_queue() which has been deprecated
- A [HC-11 wireless RF UART communication module](https://www.hc01.com/goods/640e91920be12d0114404c98) from [HC-Tech](https://www.hc01.com/). This module is not sold directly by HC-Tech but available from distributors around the world. Documentation of the module in English [here](https://www.elecrow.com/download/HC-11.pdf).
=> Updated hc11_modem to 1.1

applications/GPIO/sd_spi/manifest.yml, applications/GPIO/sd_spi_app/manifest.yml
- Lock and Unlock SD card / Micro SD card through SPI protocol.
- you need to connect an sd card to the flipper
Flipper Zero  | SD Card
------------- | -------------
9/3.3V  | +3.3V
8/GND  | GND
2/A7  | Mosi
3/A6  | Miso
4/A4  | CS
5/B3  | SCK
- [ X] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [ X] I own the code I'm submitting or have code owner's permission to submit it
- [ X] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`
=> SD SPI v0.3

applications/GPIO/flipper_gb_printer/manifest.yml
- Move pinout selection to main menu
- Update to improved pinout configuration handling w/ auto-save and auto-load pinouts
- Add fine grained save options
- Shift to new naming scheme. Files still placed in dated folder, will have date in output file name(s), as well as a globally incrementing (as opposed to reset each day) 4 digit number.
Flipper, Game Boy, Link Cable interface, Game Boy game capable of printing.
=> GPIO/flipper_gb_printer: bump to v0.4

applications/GPIO/flipperscope/manifest.yml
Added simple spectrum analyser
Unfortunately I'm not able to validate using bundle.py, as I'm using python 3.13, where _create_fn has been removed from dataclasses, so the script doesn't run correctly any more.
=> Bump flipperscope to v0.4

applications/GPIO/pokemon/manifest.yml
Fixes datatype casting issue that could result in weirdness in Gen II trades.
- Gen II pokemon game, Game Boy that can play it, Flipper link cable interface
=> GPIO/pokemon: bump to v2.3

applications/Infrared/tamagometer_companion/manifest.yml
- Tamagometer Companion lets a computer use the Flipper's IR capabilities to communicate with a Tamagotchi Connection (2024 version). It's designed to work with a web app I made (hosted on Github pages [here](https://zacharesmer.github.io/tamagometer/))
- It works by adding a `tamagometer` CLI command to the Flipper CLI while the app is open, and the tamagometer website calls that command using the Web Serial API. The GUI doesn't do anything but keep the app open.
- A computer with a serial connection to the Flipper, and a Chromium browser connected to the tamagometer web app. You could run the command to listen for or send Tamagotchi signals in minicom or something if you really wanted to, but the tamagometer web app allows for two way communication so you can actually start visits, send …
=> Add tamagometer_companion v0.2

applications/GPIO/lightmeter/manifest.yml
- Update Exposure Value compute logic
- Remove deprecated view_dispatcher_enable_queue call
- none
=> Update Lightmeter v1.3

applications/GPIO/longwave_clock/manifest.yml
- This app can receive long wave signals via GPIO modules
- Alternatively it can simulate reception if no modules are available
- Decoding the protocols is transparent in the graphical interface
- The decoded date/time is then constantly updated based on the incoming bits
- Supported are DCF77 and MSF reception.
- Optional: GPIO modules shown [in the homepage](https://github.com/m7i-org/flipper_longwave_clock). Otherwise, use simulation mode.
=> Added longwave_clock v 0.1

.gitignore, applications/Infrared/xbox_controller/manifest.yml, applications/Sub-GHz/subghz_scheduler/manifest.yml
- A Flipper Zero app to send SubGHz signals at a given interval. Individual *.sub or playlist *.txt files can be used. Discrete intervals from 10 seconds to 12 hours are selectable, as well as repeating transmissions for individual data. Updated version to fix bugs found in previous submission and to extend functionality.
- None
=>  Sub-GHz Scheduler v2.0

applications/GPIO/401_light_msg/manifest.yml
- Lab401's LightMessenger module companion, allowing users to draw text and images in the air using a 16 RGB Led array and an accelerometer. The app contains a bitmap drawing tool, a flashlight mode, configuration etc.
- This application needs a special opensource hardware called LightMessenger yet to be released.
=> lightmessenger integration

applications/USB/portal_of_flipper/manifest.yml
- Added support for xbox 360
- Added support for emulating the portals LEDs
-  Game console (non-xbox one)
-  Game (Skylanders: Giants, Skylanders: Trap Team, Skylanders: Superchargers)
=> Bump Portal of Flipper to v1.1

applications/GPIO/sio2flip/manifest.yml
sio2flip emulates SIO peripherals for Atari 8-bit computers, currently featuring floppy drive emulation and direct XEX executable loading.
- An Atari 8-bit computer (e.g., 800XL/XE, 130XE, or other compatible models)
- A wired connection between the Flipper and the Atari SIO connector
- One or more .atr or .xex files in the apps_data/sio2flip/ folder on your SD card
=> Add sio2flip v0.1

applications/GPIO/noptel_lrf_sampler/manifest.yml
New in version 2.1:
- Made passthru.c work with cli_vcp_disable() / cli_vcp_enable() when applicable (firmware 1.3.2-rc)
=> Updated noptel_lrf_sampler to 2.1

applications/Sub-GHz/hc11_modem/manifest.yml
- HC-11 wireless modem emulator for the Flipper Zero.
New in version 1.2:
- Made passthru.c work with cli_vcp_disable() / cli_vcp_enable() when applicable (firmware 1.3.2-rc)
- A [HC-11 wireless RF UART communication module](https://www.hc01.com/goods/640e91920be12d0114404c98) from [HC-Tech](https://www.hc01.com/). This module is not sold directly by HC-Tech but available from distributors around the world. Documentation of the module in English [here](https://www.elecrow.com/download/HC-11.pdf).
=> Updated hc11_modem to 1.2

tools/requirements.txt
Fixes #600 
there is also issue in fbt about `@classmethod` and `@property` being used together which will not work on 3.13, so app will not build correctly due to ufbt. i will make a pr for this in firmware repo shortly.
=> Tools: Fix for Python 3.13

.github/workflows/bundle.yml
- github: pinned tj-actions/changed-files version with sha to address recent CVE 
- no functional changes
=> github: pinned tj-actions/changed-files version with sha

applications/GPIO/sio2flip/manifest.yml
- Added Atari 850 modem emulation, with the serial connection bridged via USB CDC (virtual COM port).
- An Atari 8-bit computer (e.g., 800XL/XE, 130XE, or other compatible models)
- A wired connection between the Flipper and the Atari SIO connector
- One or more .atr or .xex files in the apps_data/sio2flip/ folder on your SD card
=> Update sio2flip to v0.2

applications/NFC/passy/manifest.yml
- Fixes crash when passport read only catches `NfcProtocolIso14443_3b`
- Fixes passports that have Q-Z in their passport number
- A passport with a Q-Z that was failing before should no longer fail
=> Bump passy to 1.2

applications/iButton/ibutton_converter/manifest.yml
**iButton Converter** is a Flipper Zero application designed for converting iButton key dumps from *Metakom* or *Cyfral* formats into the *Dallas* format. The application supports multiple conversion modes for each format, including well-known and lesser-known encoding schemes.
- Support for importing Metakom and Cyfral key dump files
- Multiple conversion modes:
- **Metakom**: 
- `direct` mode
- `reversed` mode
- **Cyfral**:
- Standard modes: `C1`, `C2`, `C3`, `C4`
- Extended modes: `C5`, `C6`, `C7`
- Output to Dallas iButton format
- Custom naming for the converted output file
=> iButton converter v1.0

applications/Tools/combo_cracker/manifest.yml
This utility assists in cracking combination pad locks by computing the necessary arithmetic to display the deduced combinations.
=> Add Combo Cracker application

applications/GPIO/noptel_lrf_sampler/manifest.yml
New in version 2.2:
- Re-enabled the use of the 5V pin (pin #&NoBreak;1) to optionally control the rangefinder's power supply, in addition to the C1 pin (pin #&NoBreak;15)
=> Updated noptel_lrf_sampler to 2.2

applications/Infrared/hitachi_ac_remote/README.md, applications/Infrared/hitachi_ac_remote/manifest.yml
- Another hard fork of the [mitsubishi_ac_remote](https://github.com/achistyakov/flipperzero-mitsubishi-ac-remote) application. This time supporting Hitachi air conditioners.
- None
=> Add hitachi_ac_remote

applications/Infrared/hitachi_ac_remote/manifest.yml
Update hitachi_ac_remote to v1.1, which implements all known features of the Hitachi PC-LH3 series remote.
- None
=> Update hitachi_ac_remote to v1.1

applications/NFC/metroflip/manifest.yml
- Fix unsupported card crash
- RENFE Suma 10 support ADDED
- GEG Connect AID added to DESfire list.
- Top Up log parsing and animations.
- 16 new rail lines, including JR lines like Chuo, Negishi, Joban, and Yamanote; and all of Tokyu's operating lines.
- Added support for parsing area codes for future expansion on non-Tokyo areas.
- Added saving function for Suica/Japan Rail IC readings.
- Various bug fixes and safer memory manegements improvements.
=> Bump Metroflip to V0.9

applications/GPIO/wiegand_reader/README.md, applications/GPIO/wiegand_reader/manifest.yml
- This application allows you to read Wiegand signals from a keypad by connecting the D0, D1 and GND wires to the Flipper Zero.
- If supported by your Wiegand reader, you can add 4.7K inline resistors and then use the application to pull the lines to ground, allowing you to resend Wiegand data.
- You can also add 2 MOSFETs to allow the Flipper Zero to tap into a Wiegand reader that requires the lines have a lower impedance.
- You need a Wiegand reader with green (D0)/white(D1) and black (GND) wires to connect to the device. (Or you could simulate it with a second Flipper Zero running the app and loading the example file from the projects GitHub example/C1.wgn file.)
- To test sending you need a few 4.7K resistors, a Wiegand reader and a Wiegand control panel. You can also simulate it …
=> wiegand_reader 1.4

applications/GPIO/401_digilab/manifest.yml
- Companion app for lab401's DigiLab hardware module, bump to v1.1.1
- require  lab401's DigiLab hardware module
=> bump to 1.1.1
